// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.build.ssci;

message InputProperties {
  // bq_artifact_table is the BQ table where artifact rows will be written
  // to it has the form project.dataset.table.
  string bq_artifact_table = 1;

  // bq_library_table is the BQ table where library rows will be written
  // to it has the form project.dataset.table.
  string bq_library_table = 2;

  // depbot_version is the version of the depbot binary to use.
  string depbot_version = 3;

  // targets is the entrypoint to the SSCI collection.
  repeated string targets = 4;

  // version of the partybot CIPD module to use
  string partybot_version = 6;

  // bq table for third party dependencies collected during the run
  string bq_thirdparty_table = 7;

  // version of the SSCI CIPD module to use
  string ssci_version = 8;

  // Whether to generate a minimal version of the SPDX file
  bool minimal_spdx = 9;
}