// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.build.ssci;

import "google/protobuf/duration.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

// Next ID: 15.
message InputProperties {
  reserved 8, 9, 13;

  // bq_artifact_table is the BQ table where artifact rows will be written
  // to it has the form project.dataset.table.
  string bq_artifact_table = 1;

  // bq_library_table is the BQ table where library rows will be written
  // to it has the form project.dataset.table.
  string bq_library_table = 2;

  // depbot_version is the version of the depbot binary to use.
  string depbot_version = 3;

  // targets is the entrypoint to the SSCI collection.
  repeated string targets = 4;

  // version of the partybot CIPD module to use
  string partybot_version = 6;

  // bq table for third party dependencies collected during the run
  string bq_thirdparty_table = 7;

  // version of the SSCI uploader CIPD binary to use.
  string ssci_uploader_version = 10;

  // enable the uploading of data collected from the various SSCI binaries.
  bool enable_upload_collected_data = 11;

  // Version of the SSCI SBOM Generator to use.
  string ssci_sbom_version = 12;

  // Whether licenses should be included when generating SBOMs.
  bool include_licenses = 14;
}

message GeneratedSBOM {
  // digest of the generated SBOM.
  string digest = 1;
  // GCS URI of the generated SBOM file.
  string file = 2;
  // Name of the artifact for which the SBOM was generated.
  string filename = 3;
  // Name of the generated SBOM.
  string sbom_name = 4;
  // Local on disk path to the generated SBOM.
  string sbom_path = 5;
  // The target used to build the SBOM, such as a GN target
  // or a reference to something a GN target outputs.
  string target = 6;
  // The same target as above however in the case of an
  // archive SBOM, multiple targets will produce a combined
  // SBOM and those targets will be here instead of the field
  // above.
  repeated string targets = 7;
}

message GenerationResult {
  // buildbucket ID.
  string buildbucket_id = 1;
  // Name of the builder.
  string builder_name = 2;
  // LUCI realm of the builder.
  string builder_realm = 3;
  // Duration to generate the SBOMs.
  google.protobuf.Duration duration = 4;
  // List of SBOMs by name.
  repeated string list_of_sboms = 5;
  // The GCS bucket the SBOM was written in by this module.
  string sbom_bucket = 6;
  // List of SBOMs generated.
  repeated GeneratedSBOM sboms_built = 7;
  // Status of the generation.
  enum Status {
    OK = 0;
    NOT_OK = 1;
  }
  Status status = 8;
  // List of targets used to produce the SBOMs.
  repeated string targets = 9;
  // Timestamp of when the generation took place.
  google.protobuf.Timestamp timestamp = 10;
  // A flexible dictionary storing arbitrary JSON data, organized
  // by unique keys. Usually this is data specific to the recipe
  // calling this module such as chromium_version or git commit.
  map<string, google.protobuf.Value> json_data = 11;
}