syntax = "proto3";

package recipes.build.devtools.compilator;

message InputProperties {
  // Configuration name for the builder (Debug/Release)
  string builder_config = 1;
  // Turn the is_official_build gn flag on (default off)
  bool is_official_build = 2;
  reserved 3;
  reserved "devtools_skip_typecheck";
  // Should the builder clean up the out/ folder before building
  bool clobber = 4;
  // Force host_cpu variable in DEPS to a specific value.
  string force_host_cpu = 5;
  // Turn the devtools_bundle gn flag off (default on)
  bool devtools_bundle = 6;
}