syntax = "proto3";

package recipes.build.devtools.trybot_tester;

message InputProperties {
  // Configuration name for the builder (Debug/Release)
  string builder_config = 1;
  // Turn the is_official_build gn flag on (default off)
  bool is_official_build = 2;
  // Turn the devtools_skip_typecheck gn flag on (default off)
  bool devtools_skip_typecheck = 3;
  // Compilator name
  string compilator_name = 4;
  // Target OS for swarming test tasks
  string target_os = 5;
  // Target cpu architecture for swarming test tasks
  string target_cpu = 6;
}