// Copyright 2021 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.build.chromium_orchestrator;

message InputProperties {
  // Name of compilator builder that is triggered to build targets
  string compilator = 1;
  // For launching sub_builds with the infra/chromium/compilator_watcher cipd
  // package.
  // git revision is for repo https://chromium.googlesource.com/infra/infra
  string compilator_watcher_git_revision = 2;

  reserved 3;
  reserved "propagate_properties_to_compilator";

  // Max number of seconds to poll compilator. If not set, defaults to 7200
  // (2 hours) in compilator_watcher.
  int64 compilator_watcher_polling_timeout_sec = 4;
}
