// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.build.chromium_toolchain.trusted_packaging;

message InputProperties {
  enum ToolchainType {
    UNKNOWN = 0;
    CLANG = 1;
    RUST = 2;
  }
  ToolchainType toolchain = 1;
  string trusted_build_instance = 2;
  string trusted_build_instance_pool = 3;
  string trusted_build_instance_env = 4;
  string trusted_build_instance_project = 5;
}
