// Copyright 2023 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.build.gofindit.chromium.test_single_revision;

// InputProperties defines the input properties being passed to
// test_single_revision.py recipe.
message InputProperties {
  // Identifies a builder compatible with chromium_tests.
  // We are not using project-bucket-id identifier here because
  // it is not compatible with chromium_tests recipe.
  message BuilderId {
    string group = 1;
    string builder = 2;
  }

  // The builder to run the test on.
  BuilderId target_builder = 1;

  // Test represents the test to rerun.
  message Test {
    string test_suite_name = 1;
    string test_name = 2;
  }

  // We support running multiple tests in the same build.
  repeated Test tests_to_run = 2;
}
