# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from recipe_engine import recipe_api
from recipe_engine.config_types import Path


class OrderfileApi(recipe_api.RecipeApi):

  def __init__(self, properties, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self._use_orderfile = properties.use_orderfile
    self._upload_orderfile = properties.upload_orderfile

  @property
  def using_orderfile(self):
    """Indicates this run uses orderfile, set in bot's *.star config files.

    Used by chromium_tests.run_tests() to process profile data when True.
    """
    return self._use_orderfile

  @property
  def upload_orderfile(self):
    """Indicates the generated orderfile should be uploaded to CIPD.

    Setting this to false allows testing the rest of the recipe but not upload
    any new orderfiles to CIPD (e.g. trybots).
    """
    return self._upload_orderfile

  def process_orderfile_data(self, source_dir: Path):
    """Processes the orderfile generated by the benchmarks.

    Args:
      source_dir: The path to the top-level repo.
    """

    with self.m.step.nest('Processing generated orderfile'):
      # TODO(crbug.com/372692473): Find the path of the generated orderfile.

      # TODO(crbug.com/372692473): Calculate branch/commit to add tag info for
      #     cipd upload (this will be useful for debugging and figuring out
      #     which branch/commit the orderfile was generated from.).

      if not self.upload_orderfile:
        return self.m.step.empty(
            'Skipping upload to CIPD for this generated orderfile as the '
            'upload_orderfile property is not enabled.')

      # TODO(crbug.com/372692473): Use self.m.cipd to upload it to an
      #     arch-specific CIPD bucket (e.g. arm64 or arm32).
      return self.m.step.empty('Uploading generated orderfile to CIPD.')
