# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import textwrap

from recipe_engine import recipe_api
from recipe_engine.config_types import Path


class OrderfileApi(recipe_api.RecipeApi):

  def __init__(self, properties, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self._use_orderfile = properties.use_orderfile
    self._upload_orderfile = properties.upload_orderfile
    self._gs_bucket = properties.gs_bucket
    self._gs_bucket_path = properties.gs_bucket_path
    self._last_uploaded_pgo_filename = properties.last_uploaded_pgo_filename

  @property
  def using_orderfile(self):
    """Indicates this run uses orderfile, set in bot's *.star config files.

    Used by chromium_tests.run_tests() to process profile data when True.
    """
    return self._use_orderfile

  @property
  def upload_orderfile(self):
    """Indicates the generated orderfile should be uploaded to CIPD.

    Setting this to false allows testing the rest of the recipe but not upload
    any new orderfiles to CIPD (e.g. trybots).
    """
    return self._upload_orderfile

  @property
  def gs_bucket(self):
    """The bucket to load the PGO profile from."""
    return self._gs_bucket

  @property
  def gs_bucket_path(self):
    """The bucket path to load the PGO profile from."""
    return self._gs_bucket_path

  @property
  def last_uploaded_pgo_filename(self):
    """The filename of the PGO profile to download."""
    return self._last_uploaded_pgo_filename

  def configure_custom_pgo_profile(self, source_dir: Path):
    """Add custom GN args to use the latest PGO profile.

    Args:
      source_dir: The path to the top-level repo.
    """
    if not self.last_uploaded_pgo_filename:
      self.m.step.empty('no custom PGO profile specified')
      return
    # This file is an empty .gni file in //src, containing just empty comments.
    # Its value is inserted into the args.gn file by mb_config.py (meta-build
    # config) as part of GN arg generation. Thus by replacing its content here
    # with the GN args necessary to use the latest PGO profile, we ensure that
    # at GN gen time the latest PGO profile is pulled and used during the build.
    override_gn_path = source_dir / 'tools/pgo/override_args.gni'
    contents = textwrap.dedent(f'''\
        pgo_override_filename = "{self.last_uploaded_pgo_filename}"
        pgo_gs_bucket = "{self.gs_bucket}"
        pgo_gs_bucket_path = "{self.gs_bucket_path}"''')
    self.m.file.write_text('override PGO profile', override_gn_path, contents)

  def process_orderfile_data(self, source_dir: Path):
    """Processes the orderfile generated by the benchmarks.

    Args:
      source_dir: The path to the top-level repo.
    """

    with self.m.step.nest('processing generated orderfile'):
      # TODO(crbug.com/372692473): Find the path of the generated orderfile.

      # TODO(crbug.com/372692473): Calculate branch/commit to add tag info for
      #     cipd upload (this will be useful for debugging and figuring out
      #     which branch/commit the orderfile was generated from.).

      if not self.upload_orderfile:
        return self.m.step.empty(
            'skipping upload to CIPD for this generated orderfile as the '
            'upload_orderfile property is not enabled')

      # TODO(crbug.com/372692473): Use self.m.cipd to upload it to an
      #     arch-specific CIPD bucket (e.g. arm64 or arm32).
      return self.m.step.empty('uploading generated orderfile to CIPD')
