# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import annotations

import textwrap

from recipe_engine import recipe_api
from recipe_engine.config_types import Path
from RECIPE_MODULES.depot_tools.bot_update.api import Result


class OrderfileApi(recipe_api.RecipeApi):

  def __init__(self, properties, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self._use_orderfile = properties.use_orderfile
    self._upload_orderfile = properties.upload_orderfile
    self._gs_bucket = properties.gs_bucket
    self._gs_bucket_path = properties.gs_bucket_path
    self._last_uploaded_pgo_filename = properties.last_uploaded_pgo_filename

  @property
  def using_orderfile(self):
    """Indicates this run uses orderfile, set in bot's *.star config files.

    Used by chromium_tests.run_tests() to process profile data when True.
    """
    return self._use_orderfile

  @property
  def upload_orderfile(self):
    """Indicates the generated orderfile should be uploaded to CIPD.

    Setting this to false allows testing the rest of the recipe but not upload
    any new orderfiles to CIPD (e.g. trybots).
    """
    return self._upload_orderfile

  @property
  def gs_bucket(self):
    """The bucket to load the PGO profile from."""
    return self._gs_bucket

  @property
  def gs_bucket_path(self):
    """The bucket path to load the PGO profile from."""
    return self._gs_bucket_path

  @property
  def last_uploaded_pgo_filename(self):
    """The filename of the PGO profile to download."""
    return self._last_uploaded_pgo_filename

  @property
  def _branch(self):
    """Parse the branch name from ref."""
    ref = self.m.buildbucket.gitiles_commit.ref
    if not ref:
      raise self.m.step.StepFailure(
          f'Missing ref: {self.m.buildbucket.gitiles_commit}')
    # Release ref: refs/branch-heads/4103
    # Main ref: refs/heads/main
    return ref.split('/', 2)[2]

  def _get_arch(self):
    """Return the architecture name used for the orderfile artifact."""
    if self.m.chromium.c.TARGET_ARCH == 'arm':
      if self.m.chromium.c.TARGET_BITS == 32:
        return 'arm'
      if self.m.chromium.c.TARGET_BITS == 64:
        return 'arm64'
    raise self.m.step.StepFailure(
        f'Unsupported arch={self.m.chromium.c.TARGET_ARCH}. Currently only '
        'arm/arm64 are supported.')

  def configure_custom_pgo_profile(self, source_dir: Path):
    """Add custom GN args to use the latest PGO profile.

    Args:
      source_dir: The path to the top-level repo.
    """
    if not self.last_uploaded_pgo_filename:
      self.m.step.empty('no custom PGO profile specified')
      return
    # This file is an empty .gni file in //src, containing just empty comments.
    # Its value is inserted into the args.gn file by mb_config.py (meta-build
    # config) as part of GN arg generation. Thus by replacing its content here
    # with the GN args necessary to use the latest PGO profile, we ensure that
    # at GN gen time the latest PGO profile is pulled and used during the build.
    override_gn_path = source_dir / 'tools/pgo/override_args.gni'
    contents = textwrap.dedent(f'''\
        pgo_override_filename = "{self.last_uploaded_pgo_filename}"
        pgo_gs_bucket = "{self.gs_bucket}"
        pgo_gs_bucket_path = "{self.gs_bucket_path}"''')
    self.m.file.write_text('override PGO profile', override_gn_path, contents)

  def _get_orderfile_package_name(self, arch, builder_name):
    """Returns the CIPD package name for the orderfile."""

    # TODO(crbug.com/445143381) This is a temporary workaround until WebView
    # orderfile builders are triggered by their own PGO builder. Currently, they
    # are triggered by Clank's PGO builder
    if 'webview' in builder_name:
      # TODO(crbug.com/445143381): This package name is temporarily set for A/B
      # testing of WebView orderfiles built from WebView PGO profiles vs from
      # Clank PGO profiles.
      if 'webview' in self.last_uploaded_pgo_filename:
        return f'chromium/android_webview/tools/orderfiles/{arch}_webview_pgo'
      return f'chromium/android_webview/tools/orderfiles/{arch}'
    return f'chromium/chrome/android/orderfiles/{arch}'

  def process_orderfile_data(self, source_dir: Path, result: Result):
    """Processes the orderfile generated by the benchmarks.

    Args:
      source_dir: The path to the top-level repo.
      result: The bot_update result from the build.
    """

    with self.m.step.nest('processing generated orderfile') as presentation:
      arch = self._get_arch()
      orderfile_name = 'orderfile.out'
      orderfile_path = self.m.profiles.profile_dir() / orderfile_name
      presentation.step_text += arch + '<br/>'
      presentation.step_text += orderfile_name + '<br/>'
      presentation.step_text += str(orderfile_path) + '<br/>'
      if not self.m.path.exists(orderfile_path):
        presentation.status = self.m.step.FAILURE
        raise self.m.step.StepFailure(
            f'Orderfile not found at {orderfile_path}')

      if not self.upload_orderfile:
        return self.m.step.empty(
            'skipping upload to CIPD for this generated orderfile as the '
            'upload_orderfile property is not enabled')

      if not self.last_uploaded_pgo_filename:
        return self.m.step.empty(
            'skipping upload to CIPD as last_uploaded_pgo_filename is not set')
      pkg_def = self.m.cipd.PackageDefinition(
          package_name=self._get_orderfile_package_name(
              arch, self.m.buildbucket.builder_name),
          package_root=self.m.profiles.profile_dir(),
      )

      if not self.m.led.led_build:
        self.m.bcid_reporter.report_stage("start")

      new_orderfile_name = f'orderfile.{arch}.out'
      new_orderfile_path = self.m.profiles.profile_dir() / new_orderfile_name
      self.m.file.move('rename orderfile', orderfile_path, new_orderfile_path)
      presentation.step_text += new_orderfile_name + '<br/>'
      presentation.step_text += str(new_orderfile_path) + '<br/>'
      pkg_def.add_file(new_orderfile_path)

      pgo_profile_path = (
          source_dir / 'chrome/build/pgo_profiles' /
          self.last_uploaded_pgo_filename)
      if not self.m.path.exists(pgo_profile_path):
        # We need to allow orderfile generation without PGO as currently arm32
        # relies on this. See https://crbug.com/430004881 for context.
        presentation.step_text += (
            str(pgo_profile_path) +
            ' profile does not exist, skipping it for CIPD upload.<br/>')
      else:
        presentation.step_text += str(pgo_profile_path) + ' exists.<br/>'
        new_pgo_profile_path = (
            self.m.profiles.profile_dir() / f'pgo_profile.{arch}.profdata')
        presentation.step_text += str(new_pgo_profile_path) + '<br/>'
        self.m.file.copy('copy over PGO profile', pgo_profile_path,
                         new_pgo_profile_path)
        pkg_def.add_file(new_pgo_profile_path)

      revision = result.manifest['src']['revision']
      tags = {
          'git_revision': revision,
          'branch': self._branch,
          'original_pgo_profile': self.last_uploaded_pgo_filename,
      }
      if not self.m.led.led_build:
        # TODO(crbug.com/372693140): Only add the latest ref if running on CI
        # not try.
        self.m.bcid_reporter.create_from_pkg(
            pkg_def, tags=tags, refs=[f'latest-{self._branch}'])

        self.m.bcid_reporter.report_stage("upload-complete")
