// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.build.orderfile;

message InputProperties {
  // Determines whether to run the cipd upload script for orderfile.
  bool use_orderfile = 1;

  // Whether to upload the generated orderfile to cipd.
  bool upload_orderfile = 2;

  // These 3 strings are passed from the pgo recipe module.
  string gs_bucket = 3;
  string gs_bucket_path = 4;
  string last_uploaded_pgo_filename = 5;
}
