// Copyright 2025 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
syntax = "proto3";

package recipes.build.pinpoint.perf_try_job;

// Pinpoint try job accepts key-value pairs as tags for metadata
message JobTag {
    // the key of the pair.
    string key = 1;
    // the value of the pair.
    string value = 2;
}

// TODO(b/422202862): Have multiple benchmarks/stories as input.
message InputProperties {
  // The bot configuration name for the new Pinpoint job.
  string configuration = 1;
  // The benchmark name for the new Pinpoint job.
  string benchmark = 2;
  // The story name for the new Pinpoint job.
  string story = 3;
  // The tags for the new Pinpoint job. E.g.:
  //   [{'key': 'origin', 'value': 'CQ'}, {'key': 'other', 'value': 'data'}]
  repeated JobTag tags = 4;
  // Test value to control whether the request should go to the dev service.
  // Currently it is supported only in legacy Pinpoint.
  bool use_staging = 5;
}