# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from recipe_engine import post_process

DEPS = [
    'recipe_engine/assertions',
    'recipe_engine/properties',
    'recipe_engine/step',
    'flakiness',
]


def _check_map_logs(check, map_steps, *args):
  """Helper function to check logs generated by _map_test_object."""
  step_data = map_steps.get('mapping new tests to test objects')
  check(step_data)
  logs = step_data.logs

  check('new_test_tuples' in logs)
  check("id1 vh1" in logs['new_test_tuples'])
  check("://m!gtest::S#T3 vh1" in logs['new_test_tuples'])
  check("://m!unknown::S#T4 vh1" in logs['new_test_tuples'])

  check('not_found' in logs)
  check('id2 vh1' in logs['not_found'])

  check('translation_failures' in logs)
  trans_fail_log = logs['translation_failures']
  check("Could not translate test_id '://m!unknown::S#T4'" in trans_fail_log)
  check("Falling back to test_name 'Test4'" in trans_fail_log)


def RunSteps(api):
  """Dispatch to test different parts of the api based on properties."""

  # Test cases for _get_legacy_filter_from_test_id
  if api.properties.get('run_legacy_filter_tests'):
    test_cases = api.properties.get('legacy_filter_test_cases', [])
    for i, (test_id, expected) in enumerate(test_cases):
      with api.step.nest(f'legacy filter test {i}'):
        actual = api.flakiness._get_legacy_filter_from_test_id(test_id)
        api.assertions.assertEqual(actual, expected,
                                   f"Failed for test_id: {test_id}")

  # Test case for _map_test_object
  if api.properties.get('run_map_test_object'):

    class FakeIndividualTest:

      def __init__(self, test_id, test_name, duration_milliseconds):
        self.test_id = test_id
        self.test_name = test_name
        self.duration_milliseconds = duration_milliseconds

    class FakeSuiteResult:

      def __init__(self, variant_hash, all_tests):
        self.variant_hash = variant_hash
        self.all_tests = all_tests

    class FakeTest:

      def __init__(self, name, suite_results):
        self.name = name
        self.suite_results = suite_results
        self.get_rdb_results_calls = []

      def get_rdb_results(self, suffix):
        self.get_rdb_results_calls.append(suffix)
        return self.suite_results

    test1 = FakeIndividualTest('id1', 'Test1', 10)
    test2 = FakeIndividualTest('id2', 'Test2', 20)  # Not in new_tests
    test3 = FakeIndividualTest('://m!gtest::S#T3', 'Test3', 30)
    test4 = FakeIndividualTest('://m!unknown::S#T4', 'Test4', 40)

    suite_results = FakeSuiteResult('vh1', [test1, test2, test3, test4])
    fake_test_obj = FakeTest('my_test_suite', suite_results)

    new_test_tuples = {
        ('id1', 'vh1'),
        ('://m!gtest::S#T3', 'vh1'),
        ('://m!unknown::S#T4', 'vh1'),
    }
    result_map = api.flakiness._map_test_object([fake_test_obj],
                                                new_test_tuples)

    api.assertions.assertEqual(fake_test_obj.get_rdb_results_calls,
                               ['with patch'])

    api.assertions.assertIn(fake_test_obj, result_map)
    filters, total_duration = result_map[fake_test_obj]
    api.assertions.assertIn('Test1', filters)
    api.assertions.assertIn('S.T3', filters)
    api.assertions.assertIn('Test4', filters)
    api.assertions.assertEqual(len(filters), 3)
    api.assertions.assertEqual(total_duration, 10 + 30 + 40)


def GenTests(api):
  """Generate test cases for the flakiness api."""

  # Test for _get_legacy_filter_from_test_id method
  legacy_filter_tests = [
      (None, None),
      ('', None),
      ('invalid', None),
      ('://malformed', None),
      ('://m/mod!pyunit:pkg.mod:Class#test_method', 'Class.test_method'),
      ('://target!gtest::Suite#Test', 'Suite.Test'),
      ('://target!gtest::Suite#Test/Param', 'Suite.Test/Param'),
      ('://target!xctest::Class#method', 'Class/method'),
      ('://target!junit:pkg.foo:Class#method', 'pkg.foo.Class#method'),
      ('://target!junit:pkg.foo:Outer$Inner#method',
       'pkg.foo.Outer$Inner#method'),
      ('://target!flat:::some_test_name#some_test_name', 'some_test_name'),
      ('://t!gtest::S#T\\:WithColon', 'S.T:WithColon'),
      ('://t!gtest::S#T\\\\WithBackslash', 'S.T\\WithBackslash'),
      ('://target!unknown:::Class#method', None),
  ]
  yield api.test(
      'get_legacy_filter_from_test_id',
      api.properties(
          run_legacy_filter_tests=True,
          legacy_filter_test_cases=legacy_filter_tests),
      api.post_process(post_process.DropExpectation),
  )

  # Test for _map_test_object method
  yield api.test(
      'map_test_object',
      api.properties(run_map_test_object=True),
      api.post_process(_check_map_logs, post_process.StatusSuccess),
      api.post_process(post_process.DropExpectation),
  )
