// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.build.chromium_compilator;

// Next ID: 10
message InputProperties {
  message Orchestrator {
    string builder_name = 1;
    string builder_group = 2;
  }

  // Orchestrator builder that triggered this Compilator build
  Orchestrator orchestrator = 1;

  // When set, the compilator will skip performing analysis and include the
  // reasons in the placeholder step that is emitted instead.
  repeated string skip_analysis_reasons = 8;

  // When this field is absent, the Compilator will compile (with patch) all
  // targets affected by the patch.
  // When this field is populated, the Compilator will compile these targets
  // without a patch.
  // This could be both or either swarming or skylab tests
  repeated string test_targets = 6;

  // Sets which revision to check out for the dependency
  // Maps dependency repo's path name (like 'src/v8') to revision
  // This is required for other non-src projects running a builder using
  // orchestrators and compilators
  map<string, string> deps_revision_overrides = 3;

  // Sets which revision to check out for chromium/src
  // This is required for other non-src projects running a builder using
  // orchestrators and compilators
  string root_solution_revision = 4;

  reserved 2, 5, 7, 9;
  reserved "swarming_targets", "rts_setting", "skip_tests", "rts_model";
}
