#!/usr/bin/env python3
# Copyright 2018 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""This script generates the line number mapping from bot to Gerrit.

For example:

On Gerrit, 'test.txt' is generated by applying my change to base revision 10:
#1: line 1
#2: line 2, changed by me
#3: line 3

On the bot, 'test.txt' is generated by applying my change to base revision 12:
#1: line 0, added by someone else
#2: line 1, changed by someone else
#3: line 2, changed by me

After rebasing the line numbers, we'd like understand that
'line 2, changed by me' exists in both files (it should, because both two files
contain my change), and their line number mapping is 2 -> 3.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile

import diff_util
import gerrit_util

import signal

_DEFAULT_TIMEOUT = 15 * 60


def rebase_line_number(
  host,
  project,
  change,
  patchset,
  src_path,
  sources,
  token_path=None,
  project_checkout_path=None,
  base_checkout_path='src',
):
  """Rebases line number for a list of files from bot to gerrit.

  Args:
    host (str): The url of the Gerrit host.
    project (str): The Gerrit project name.
    change (int): The Gerrit change number.
    patchset (int): The Gerrit patchset number.
    src_path (str): Absolute path to the root of the checkout.
    sources (list): A list of relative path to the source files affected by the
                    patchset, whether added, modified or deleted.
    token_path (Optional[str]): Path to file with oauth token, if applicable.
    project_checkout_path (Optional[str]): Local path to the repo where the Gerrit
                                           patch will be applied.
    base_checkout_path (str): Base path of the gclient checkout.

  The |sources| is the list of affected files generated by command 'git diff',
  so deleted files are included, this script makes requests to Gerrit to fetch
  file content for each of the given source, and a non-exist file results in
  errors, so they need to be excluded.

  Returns:
    A map whose key is a file name that is relative to the root of the checkout,
    and the corresponding value is another map that maps from local file's line
    number to Gerrit file's line number as well as the line itself.
  """
  # Remove deleted files by the patch.
  valid_sources = []
  for s in sources:
    if os.path.isfile(os.path.join(src_path, s)):
      valid_sources.append(s)
    else:
      logging.info(
        'Skipping file "%s" from line-rebase, as it is deleted by the patch', s
      )

  project_prefix = ''
  if project_checkout_path:
    project_checkout_path = project_checkout_path.replace('\\', '/')
  if base_checkout_path:
    base_checkout_path = base_checkout_path.replace('\\', '/')

  if project_checkout_path and project_checkout_path.startswith(
    base_checkout_path + '/'
  ):
    project_prefix = project_checkout_path[len(base_checkout_path) + 1 :]
    if project_prefix and not project_prefix.endswith('/'):
      project_prefix += '/'

  def to_gerrit_path(s):
    return (
      s[len(project_prefix) :]
      if (project_prefix and s.startswith(project_prefix))
      else s
    )

  gerrit_sources = [to_gerrit_path(s) for s in valid_sources]
  gerrit_files_content = gerrit_util.fetch_files_content(
    host, project, change, patchset, gerrit_sources, token_path=token_path
  )
  assert len(valid_sources) == len(gerrit_files_content), (
    'Number of files to rebase is expected to be the same as number of files '
    'have file content fetched from Gerrit'
  )

  file_to_line_num_mapping = {}
  for filename, content in zip(valid_sources, gerrit_files_content):
    if not content:
      continue
    local_file_path = os.path.join(src_path, filename)
    gerrit_file_path = None
    # On Windows, the file returned by NamedTemporaryFile cannot be opened a
    # second time by its name until it has been closed. Therefore we must ensure
    # it is closed before passing its name to the subprocess.
    with tempfile.NamedTemporaryFile(delete=False, mode='w') as gerrit_file:
      gerrit_file.write(content)
      gerrit_file_path = gerrit_file.name
    try:
      diff_cmd = [
        'git',
        'diff',
        '--no-index',
        local_file_path,
        gerrit_file_path,
      ]
      diff_output = None
      logging.info(
        'Calculating diff b/w bot file %s and gerrit file %s',
        local_file_path,
        gerrit_file_path,
      )
      # 'diff' command returns 0 if two files are the same, 1 if differences are
      # found, >1 if an error occurred.
      diff_output = subprocess.check_output(diff_cmd, text=True)
    except subprocess.CalledProcessError as e:
      if e.returncode != 1:
        raise
      diff_output = e.output
    finally:
      os.remove(gerrit_file_path)

    diff_lines = diff_output.splitlines()
    with open(local_file_path) as f:
      local_lines = f.read().splitlines()
    gerrit_lines = content.splitlines()
    file_to_line_num_mapping[filename] = diff_util.generate_line_number_mapping(
      diff_lines, local_lines, gerrit_lines
    )

  return file_to_line_num_mapping


def _parse_args():
  arg_parser = argparse.ArgumentParser()
  arg_parser.usage = __doc__

  arg_parser.add_argument(
    '--host', required=True, type=str, help='The url of the Gerrit host.'
  )

  arg_parser.add_argument(
    '--project', required=True, type=str, help='The Gerrit project name'
  )

  arg_parser.add_argument(
    '--change', required=True, type=int, help='The Gerrit change number.'
  )

  arg_parser.add_argument(
    '--patchset', required=True, type=int, help='The Gerrit patchset number.'
  )

  arg_parser.add_argument(
    '--src-path',
    required=True,
    type=str,
    help='absolute path to the root of the checkout',
  )

  arg_parser.add_argument(
    '--output-file',
    required=True,
    type=str,
    help='Path to a file where the line number mapping is written to, and '
    'the format of the mapping is a map whose key is a file name that is '
    'relative to the root of the checkout, and the corresponding value is '
    'another map that maps from local file\'s line number to Gerrit file\'s '
    'line number as well as the line itself.',
  )

  arg_parser.add_argument(
    '--token-path',
    type=str,
    help='path to file with oauth token string to pass to server',
  )

  arg_parser.add_argument(
    '--project-checkout-path',
    type=str,
    default=None,
    help='Local path to the repo where gerrit patch will be applied '
    '(e.g. src/third_party/catapult)',
  )

  arg_parser.add_argument(
    '--base-checkout-path',
    type=str,
    default='src',
    help='Base path of the gclient checkout (e.g. src)',
  )

  arg_parser.add_argument(
    '--timeout',
    required=False,
    type=int,
    default=_DEFAULT_TIMEOUT,
    help='Number of seconds after which this command will timeout and raise '
    'an Exception. Default timeout is 15 minutes.',
  )

  arg_parser.add_argument(
    'sources',
    nargs='+',
    help='Paths of source files to line number mapping for, the paths are '
    'relative to the root of the checkout, with platform-specific path '
    'separator.',
  )

  return arg_parser.parse_args()


def timeout_exception(num, stack):
  raise TimeoutError("Step 'Rebase line number from bot to gerrit' timed-out")


def initiate_timer(timeout):
  signal.signal(signal.SIGALRM, timeout_exception)
  timeout_seconds = int(timeout) or _DEFAULT_TIMEOUT
  signal.alarm(timeout_seconds)


def main():
  args = _parse_args()

  logging.basicConfig(
    level=logging.INFO, format='[%(asctime)s %(levelname)s] %(message)s'
  )
  if not os.path.isdir(args.src_path):
    raise RuntimeError('Checkout: "%s" doesn\'t exist.' % args.src_path)

  initiate_timer(args.timeout)

  file_to_line_num_mapping = rebase_line_number(
    args.host,
    args.project,
    args.change,
    args.patchset,
    args.src_path,
    args.sources,
    args.token_path,
    args.project_checkout_path,
    args.base_checkout_path,
  )
  json_mapping = json.dumps(file_to_line_num_mapping, separators=(',', ':'))
  with open(args.output_file, 'w') as f:
    f.write(json_mapping)

  sys.stdout.write(json_mapping)


if __name__ == '__main__':
  sys.exit(main())
