// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.build.chromium_rr.test_launcher;


// Next ID: 2
message InputProperties {

  // Information about the target test to run
  //
  // The runner builder will compile all input test suites and run tests using
  // the rr tool in a runner script.
  //
  // Next ID: 4
  message TestInfo {
    // The name of test suite for the target test
    string test_suite = 1;

    // The name of target test
    string test_name = 2;

    // The bug id of target test
    optional string bug_id = 3;
  }
  repeated TestInfo target_test_infos = 1;
}
