# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import datetime
from recipe_engine import post_process

from PB.go.chromium.org.luci.buildbucket.proto import common as common_pb
from PB.recipe_engine import result as result_pb2

DEPS = [
    'chromium',
    'chromium_checkout',
    'depot_tools/depot_tools',
    'depot_tools/gerrit',
    'depot_tools/git',
    'depot_tools/git_cl',
    'depot_tools/gclient',
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/file',
    'recipe_engine/json',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'recipe_engine/time',
]

COMMIT_MESSAGE = """
Autoshard chromium/src test suites

This is an automated CL generated by the autosharder.
Optimal shard counts for test suites are calculated by querying recent
runtimes.

The build that created this CL was https://ci.chromium.org/b/{}
"""


def RunSteps(api):
  """Creates a CL to update test suite shards in chromium/src
  """
  api.gclient.set_config('chromium')
  api.chromium.set_config('chromium')
  api.chromium_checkout.ensure_checkout()

  # Check if it's been at least 7 days since the last merged reshard CL
  last_merged_change_list = api.gerrit.get_changes(
      name='get last merged change',
      host='https://chromium-review.googlesource.com',
      query_params=[('owner', 'chromium-autosharder'), ('status', 'merged')],
      limit=1,
  )
  if last_merged_change_list:
    last_merged_date = datetime.datetime.strptime(
        last_merged_change_list[0]['updated'],
        '%Y-%m-%d %H:%M:%S.%f000').date()
    current_date = datetime.date.fromtimestamp(api.time.time())
    # Only look up to Monday in order to maintain the same cadence when a CL
    # isn't merged the first time
    start_of_week = current_date - datetime.timedelta(
        days=current_date.weekday() % 7)
    if (last_merged_date >= start_of_week):
      return result_pb2.RawResult(
          status=common_pb.SUCCESS,
          summary_markdown=(
              'Skipping autosharder CL creation because it has been merged '
              'this week.'),
      )

  # Check to see if there's already an active autosharder CL
  changes = api.gerrit.get_changes(
      name='get active changes',
      host='https://chromium-review.googlesource.com',
      query_params=[('uploader', 'chromium-autosharder'), ('status', 'open')],
  )

  if changes:
    if len(changes) > 1:
      return result_pb2.RawResult(
          status=common_pb.INFRA_FAILURE,
          summary_markdown=(
              'More than one autosharder CL exists. There should only be a max '
              'of one CL at any time.'),
      )

    issue_num = changes[0]['_number']
    with api.context(cwd=api.chromium_checkout.src_dir):
      status_step = api.git_cl(
          'status', ['--issue', issue_num, '--field', 'status'],
          name='git cl status',
          stdout=api.raw_io.output_text(),
          step_test_data=lambda: api.raw_io.test_api.stream_output_text(
              'commit', stream='stdout'))
      cl_status = status_step.stdout.strip()
      status_step.presentation.step_text = cl_status
    # Exit if currently open CL is running a CQ attempt
    if cl_status in ['dry-run', 'commit']:
      return result_pb2.RawResult(
          status=common_pb.SUCCESS,
          summary_markdown=(
              'There is already a CL running a CQ attempt or ready '
              'to submit.'),
      )
    # Close CL so we can upload a new one
    with api.context(cwd=api.chromium_checkout.src_dir):
      api.git_cl('set-close', ['--issue', issue_num], name='git cl set-close')

  api.git('config', 'user.name', 'autosharder')
  api.git('branch', '-D', 'autoshard', ok_ret='any')
  api.git('restore', '--staged', '.')
  with api.depot_tools.on_path():
    api.git('new-branch', 'autoshard', '--upstream', 'origin/main')

  potential_autoshard_exceptions_paths = (
      api.chromium_checkout.src_dir.join('infra', 'config', 'targets',
                                         'autoshard_exceptions.json'),
      api.chromium_checkout.src_dir.join('testing', 'buildbot',
                                         'autoshard_exceptions.json'),
  )
  for autoshard_exceptions_path in potential_autoshard_exceptions_paths:
    if api.path.exists(autoshard_exceptions_path):
      break
  else:
    step_text = ['', "none of the following file paths exist"]
    for p in potential_autoshard_exceptions_paths:
      step_text.append(f'* {p}')
    api.step.empty(
        'autoshard exceptions file not found',
        status=api.step.EXCEPTION,
        step_text='\n'.join(step_text))

  script_path = api.chromium_checkout.src_dir.join(
      'testing', 'buildbot', 'query_optimal_shard_counts.py')

  script_cmd = [
      'vpython3',
      script_path,
      '--output-file',
      autoshard_exceptions_path,
      '-v',
  ]
  api.step('which bq', ['which', 'bq'])
  api.step(
      'query optimal shards',
      script_cmd,
  )

  def step_test_data():
    autoshard_exceptions_rel_path = api.path.relpath(
        autoshard_exceptions_path, api.chromium_checkout.src_dir)
    return api.raw_io.test_api.stream_output_text(
        f'diff --git a/{autoshard_exceptions_rel_path}'
        f' b/{autoshard_exceptions_rel_path}')

  diff_step = api.git(
      'diff', stdout=api.raw_io.output_text(), step_test_data=step_test_data)
  diff_step.presentation.logs['stdout'] = diff_step.stdout
  if not diff_step.stdout:
    return

  # Output step with file contents in case we need to debug the build
  api.file.read_json(
      'read autoshard_exceptions.json',
      autoshard_exceptions_path,
  )

  regen_path = api.chromium_checkout.src_dir.join('testing', 'buildbot',
                                                  'generate_buildbot_json.py')
  api.step('regenerate test specs', ['vpython3', regen_path])

  commit_message = COMMIT_MESSAGE.format(api.buildbucket.build.id)
  api.git('commit', 'testing/buildbot', '-m', 'Autoshard test suites')
  upload_args = [
      '--cq-dry-run',
      '--bypass-hooks',
      '--enable-auto-submit',
      '-r',
      'kimstephanie@google.com',
      '--cc',
      ','.join([
          'sshrimp@google.com',
          'gatong@google.com',
      ]),
      '--send-email',
  ]

  with api.context(cwd=api.chromium_checkout.src_dir):
    api.git_cl.upload(commit_message, upload_args, name='git cl upload')
    api.git_cl(
        'issue',
        ['--json', api.json.output()],
        name='git cl issue',
    )


def GenTests(api):
  # Simulate running on a Monday
  current_timestamp = int(datetime.datetime(2023, 7, 3).timestamp())

  autoshard_exceptions_json_path = api.path['cache'].join(
      'builder', 'src', 'testing', 'buildbot', 'autoshard_exceptions.json')

  yield api.test(
      'basic',
      api.time.seed(current_timestamp),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.post_process(post_process.MustRun, 'git cl status'),
      api.post_process(post_process.DoesNotRun, 'query optimal shards'),
      api.post_process(post_process.DoesNotRun, 'regenerate test specs'),
      api.post_process(post_process.DoesNotRun, 'git cl set-close'),
      api.post_process(post_process.DoesNotRun, 'git cl upload'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'no_change',
      api.time.seed(current_timestamp),
      api.path.exists(autoshard_exceptions_json_path),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          stdout=api.raw_io.output_text(''),
      ),
      api.override_step_data(
          'git diff',
          stdout=api.raw_io.output_text(''),
      ),
      api.post_process(post_process.MustRun, 'query optimal shards'),
      api.post_process(post_process.DoesNotRun, 'regenerate test specs'),
      api.post_process(post_process.DoesNotRun, 'git cl upload'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'already merged this week',
      api.time.seed(current_timestamp),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    3).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.post_process(
          post_process.SummaryMarkdown,
          'Skipping autosharder CL creation because it has been merged '
          'this week.'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'too_many_existing_cls',
      api.time.seed(current_timestamp),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          api.json.output([{
              'subject': 'Autosharder CL',
              '_number': '12346',
          }, {
              'subject': 'Autosharder CL',
              '_number': '12347'
          }]),
      ),
      api.post_process(post_process.DoesNotRun, 'query optimal shards'),
      api.post_process(post_process.DoesNotRun, 'regenerate test specs'),
      api.post_process(post_process.DoesNotRun, 'git cl set-close'),
      api.post_process(post_process.DoesNotRun, 'git cl upload'),
      api.expect_status('INFRA_FAILURE'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'no_existing_cl',
      api.time.seed(current_timestamp),
      api.path.exists(autoshard_exceptions_json_path),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          stdout=api.raw_io.output_text(''),
      ),
      api.post_process(post_process.MustRun, 'query optimal shards'),
      api.post_process(post_process.MustRun, 'regenerate test specs'),
      api.post_process(post_process.DoesNotRun, 'git cl set-close'),
      api.post_process(post_process.MustRun, 'git cl upload'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'no_landed_CL_yet',
      api.time.seed(current_timestamp),
      api.override_step_data(
          'gerrit get last merged change',
          stdout=api.raw_io.output_text(''),
      ),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'current_dry_run',
      api.time.seed(current_timestamp),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          api.json.output([{
              'subject': 'Autosharder CL',
              '_number': '12346',
          }]),
      ),
      api.override_step_data(
          'git cl status',
          stdout=api.raw_io.output_text('dry-run'),
      ),
      api.post_process(post_process.DoesNotRun, 'query optimal shards'),
      api.post_process(post_process.DoesNotRun, 'regenerate test specs'),
      api.post_process(post_process.DoesNotRun, 'git cl set-close'),
      api.post_process(post_process.DoesNotRun, 'git cl upload'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'existing_waiting_cl',
      api.time.seed(current_timestamp),
      api.path.exists(autoshard_exceptions_json_path),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          api.json.output([{
              'subject': 'Autosharder CL',
              '_number': '12346',
          }]),
      ),
      api.override_step_data(
          'git cl status',
          stdout=api.raw_io.output_text('waiting'),
      ),
      api.post_process(post_process.MustRun, 'git cl set-close'),
      api.post_process(post_process.MustRun, 'query optimal shards'),
      api.post_process(post_process.MustRun, 'regenerate test specs'),
      api.post_process(post_process.MustRun, 'git cl upload'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'new autoshard exceptions path',
      api.time.seed(current_timestamp),
      api.path.exists(api.path['cache'].join('builder', 'src', 'infra',
                                             'config', 'targets',
                                             'autoshard_exceptions.json')),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          stdout=api.raw_io.output_text(''),
      ),
      api.override_step_data(
          'git diff',
          stdout=api.raw_io.output_text(''),
      ),
      api.post_process(post_process.MustRun, 'query optimal shards'),
      api.post_process(post_process.DoesNotRun, 'regenerate test specs'),
      api.post_process(post_process.DoesNotRun, 'git cl upload'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'no autoshard exceptions',
      api.time.seed(current_timestamp),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          stdout=api.raw_io.output_text(''),
      ),
      api.expect_status('INFRA_FAILURE'),
      api.post_process(post_process.MustRun,
                       'autoshard exceptions file not found'),
      api.post_process(post_process.DropExpectation),
  )
