# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import copy
import datetime
import math
from recipe_engine import post_process
from recipe_engine import recipe_api

from PB.recipes.build.chromium.autosharder import InputProperties
from PB.go.chromium.org.luci.buildbucket.proto import common as common_pb
from PB.recipe_engine import result as result_pb2

DEPS = [
    'chromium',
    'chromium_checkout',
    'depot_tools/depot_tools',
    'depot_tools/gerrit',
    'depot_tools/git',
    'depot_tools/git_cl',
    'depot_tools/gclient',
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/file',
    'recipe_engine/json',
    'recipe_engine/led',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'recipe_engine/time',
]

COMMIT_MESSAGE = """
Autoshard chromium/src test suites

This is an automated CL generated by the autosharder.
Optimal shard counts for test suites are calculated by querying recent
runtimes.

The build that created this CL was https://ci.chromium.org/b/{}

Ignore-Freeze:True
"""

_CLOUD_PROJECT_ID = 'chrome-trooper-analytics'

# TODO(http://crbug.com/407846444): Move these to builder config
# All suites triggered by the builder will not be autosharded.
BUILDER_EXCLUDE_SET = set([
    'mac-rel',
    'mac14-arm64-rel',
    'ios-simulator',
    'ios-simulator-full-configs',
    'android-arm64-rel',
])

# Test suites will not be autosharded on all builders that run the test suite.
# Example: 'browser_tests' -> turns of browser_tests on linux-rel and win-rel
TEST_SUITE_EXCLUDE_SET = set([
    # 'chrome_all_tast_tests': crbug.com/1516971
    'chrome_all_tast_tests',
])

# Test suite and try builder dicts that should not be autosharded any further.
# Maps try builder to set of test suite
# Example: {'linux-rel': {'browser_tests'}}
BUILDER_TEST_SUITE_EXCLUDE_DICT = {}

# Minimum number of non-experimental samples to allow a suite to be
# resharded
MIN_SAMPLE_SIZE = 1500
# The percentile that must meet the target runtime
PERCENTILE = 80

# TODO(crbug.com/40281184): Replace with queried, per-suite overheads, once
# infra is set up to support automated overhead measurements.
# See go/nplus1shardsproposal
DEFAULT_OVERHEAD_MIN = 1.0
ANDROID_OVERHEAD_MIN = 2.0

# Clamp values for test overheads.
MIN_OVERHEAD_MIN = 0.2
MAX_OVERHEAD_MIN = 4.0

PROPERTIES = InputProperties


def RunSteps(api, properties):
  """Creates a CL to update test suite shards in chromium/src
  """
  api.gclient.set_config('chromium')
  api.chromium.set_config('chromium')

  api.chromium_checkout.ensure_checkout()
  maybe_result = check_run_conditions(api)
  if maybe_result:
    return maybe_result

  setup_git(api)

  potential_autoshard_exceptions_paths = (
      api.chromium_checkout.source_dir.joinpath('infra', 'config', 'targets',
                                                'autoshard_exceptions.json'),
      api.chromium_checkout.source_dir.joinpath('testing', 'buildbot',
                                                'autoshard_exceptions.json'),
  )

  for autoshard_exceptions_path in potential_autoshard_exceptions_paths:
    if api.path.exists(autoshard_exceptions_path):
      break
  else:
    step_text = ['', "none of the following file paths exist"]
    for p in potential_autoshard_exceptions_paths:
      step_text.append(f'* {p}')
    api.step.empty(
        'autoshard exceptions file not found',
        status=api.step.EXCEPTION,
        step_text='\n'.join(step_text))

  calculate_optimal_shards(api, properties.target_runtime)

  def step_test_data():
    autoshard_exceptions_rel_path = api.path.relpath(
        autoshard_exceptions_path, api.chromium_checkout.source_dir)
    return api.raw_io.test_api.stream_output_text(
        f'diff --git a/{autoshard_exceptions_rel_path}'
        f' b/{autoshard_exceptions_rel_path}')

  diff_step = api.git(
      'diff', stdout=api.raw_io.output_text(), step_test_data=step_test_data)
  diff_step.presentation.logs['stdout'] = diff_step.stdout
  if not diff_step.stdout:
    return

  # Output step with file contents in case we need to debug the build
  api.file.read_json(
      'read autoshard_exceptions.json',
      autoshard_exceptions_path,
  )

  with api.step.nest('regenerate targets specs'):
    src_dir = api.chromium_checkout.source_dir
    api.step(
        '//testing/buildbot',
        ['vpython3', src_dir / 'testing/buildbot/generate_buildbot_json.py'])

    api.step('//infra/config prod', [src_dir / 'infra/config/main.star'])

  if not api.led.led_build:
    commit_message = COMMIT_MESSAGE.format(api.buildbucket.build.id)
    api.git('commit', '-a', '-m', 'Autoshard test suites')
    upload_args = [
        '--cq-dry-run',
        '--bypass-hooks',
        '--enable-auto-submit',
        '-r',
        'rubber-stamper@appspot.gserviceaccount.com',
        '--cc',
        ','.join([
            'gatong@google.com',
            'sshrimp@google.com',
            'chrome-dev-infra-auto+reviews@google.com',
        ]),
        '--send-email',
    ]

    with api.context(cwd=api.chromium_checkout.source_dir):
      api.git_cl.upload(commit_message, upload_args, name='git cl upload')
      api.git_cl(
          'issue',
          ['--json', api.json.output()],
          name='git cl issue',
      )


def calculate_optimal_shards(api, target_runtime):
  api.step('which bq', ['which', 'bq'])

  today = api.time.utcnow()
  start = today - datetime.timedelta(days=14)
  lookback_start_date = start.strftime('%Y-%m-%d')
  lookback_end_date = today.strftime('%Y-%m-%d')

  durations = query_durations(
      api,
      target_runtime,
      lookback_start_date,
      lookback_end_date,
  )

  overhead_dict = query_overheads(
      api,
      lookback_start_date,
      lookback_end_date,
  )

  durations_with_optimal_shards = _calculate_and_filter_optimal_shard_counts(
      overhead_dict, durations, target_runtime)

  durations_with_optimal_shards_and_bot_hours = (
      _calculate_estimated_bot_hour_cost(
          api,
          durations=durations_with_optimal_shards,
          lookback_start_date=lookback_start_date,
          lookback_end_date=lookback_end_date,
      ))

  exceptions_file = api.chromium_checkout.source_dir.joinpath(
      'infra', 'config', 'targets', 'autoshard_exceptions.json')
  data = api.m.file.read_json(
      'read current exceptions file', exceptions_file, test_data={})

  new_data = {}
  for r in durations_with_optimal_shards_and_bot_hours:
    builder_group = r['waterfall_builder_group']
    builder_name = r['waterfall_builder_name']
    test_suite = r['test_suite']
    if not _meets_optimal_shard_count_and_simulated_duration_requirements(
        r, data, target_runtime):
      continue
    shard_dict = {
        test_suite: {
            'shards': r['optimal_shard_count'],
            'try_builder': r['try_builder'],
        },
    }
    debug_dict = {
        'avg_num_builds_per_peak_hour':
            r['avg_num_builds_per_peak_hour'],
        'estimated_bot_hour_delta':
            r['estimated_bot_hour_cost'],
        'prev_avg_pending_time_sec':
            float(r['avg_pending_time_sec']),
        'prev_p50_pending_time_sec':
            float(r['p50_pending_time_sec']),
        'prev_p90_pending_time_sec':
            float(r['p90_pending_time_sec']),
        'prev_percentile_duration_minutes':
            float(r['percentile_duration_minutes']),
        'prev_shard_count':
            int(r['shard_count']),
        'simulated_max_shard_duration':
            r['simulated_max_shard_duration'],
        'test_overhead_min':
            r['test_overhead_min'],
    }
    shard_dict[r['test_suite']]['debug'] = debug_dict
    data.setdefault(builder_group, {}).setdefault(builder_name,
                                                  {}).update(shard_dict)
    new_data.setdefault(builder_group, {}).setdefault(builder_name,
                                                      {}).update(shard_dict)

  _prune_builders(api, data)

  api.file.write_json(
      'write exceptions file',
      exceptions_file,
      data,
      indent=4,
  )


def _meets_optimal_shard_count_and_simulated_duration_requirements(
    row, data, desired_runtime):
  builder_group = row['waterfall_builder_group']
  builder_name = row['waterfall_builder_name']
  test_suite = row['test_suite']

  current_autoshard_val = data.get(builder_group,
                                   {}).get(builder_name,
                                           {}).get(test_suite, {}).get('shards')

  # No autosharding needed.
  if int(row['optimal_shard_count']) == int(row['shard_count']):
    return False

  # Throw out any attempt to shard to 1. This will lock the test suite
  # and prevent go/nplus1shardsproposal from running new shardings
  if int(row['optimal_shard_count']) == 1:
    return False

  # Don't bother resharding if the simulated runtime is greater than the
  # desired runtime.
  if float(
      row['simulated_max_shard_duration']) > desired_runtime:  # pragma: nocover
    return False

  # Shard values may have changed over the lookback period, so the query
  # results could have multiple rows for each builder+test_suite. Logic below
  # skips the rows that are for outdated shard counts.

  # First check if this suite has been autosharded before
  # If it has been autosharded before, we should only look at the row
  # containing a matching 'shard_count' with the current autoshard value.
  if current_autoshard_val:
    # If this row does not match, skip it. This row is for an old shard count
    # that is no longer being used.
    if int(current_autoshard_val) != int(row['shard_count']):
      return False
  else:
    # Query suggests we should decrease shard count for suite that has
    # never been autosharded
    if int(row['optimal_shard_count']) < int(row['shard_count']):
      # Only use lower shard count value if the suite was previously
      # autosharded.
      # This is because the suite could have been previously autosharded with
      # more shards due to a test regression. If the regression is fixed, that
      # suite should have those extra shards removed.
      # There's many existing suites that already run pretty fast from
      # previous manual shardings. Those technically can have fewer shards as
      # well, but let's leave those alone until we have a good reason to
      # change a bunch of suites at once.
      return False
  return True


def _calculate_and_filter_optimal_shard_counts(overhead_dict, durations,
                                               desired_runtime):
  filtered_durations = []
  for r in durations:
    try_builder = r['try_builder']
    test_suite = r['test_suite']
    shard_count = int(r['shard_count'])

    overhead = overhead_dict.get(try_builder, {}).get(test_suite,
                                                      {}).get(shard_count)
    if overhead:
      # Suites can be in a bad sharding. Since we only use one set of shards
      # (n and n+1) this can create a bad value for the overhead so clamp it
      # to reasonable values. At the time of writing this the min and max are
      # around 0.21 and 4.01. Ideally we could use more than one set of
      # shardings to determine this overhead.
      overhead = max(min(overhead, MAX_OVERHEAD_MIN), MIN_OVERHEAD_MIN)
    else:
      if 'android' in try_builder:
        overhead = ANDROID_OVERHEAD_MIN
      else:
        overhead = DEFAULT_OVERHEAD_MIN
    r['test_overhead_min'] = overhead

    optimal_shard_count = math.ceil(
        (float(r['percentile_duration_minutes']) * shard_count -
         overhead * shard_count) / (desired_runtime - overhead))
    if optimal_shard_count <= 0:
      continue
    r['optimal_shard_count'] = optimal_shard_count

    overhead_change = (optimal_shard_count - shard_count) * overhead
    simulated_max_shard_duration = round(
        ((float(r['percentile_duration_minutes']) * shard_count +
          overhead_change) / optimal_shard_count), 2)
    r['simulated_max_shard_duration'] = simulated_max_shard_duration

    filtered_durations.append(r)
  return filtered_durations


def _calculate_estimated_bot_hour_cost(api, durations, lookback_start_date,
                                       lookback_end_date):
  results = _query_avg_num_builds_per_hour(
      api,
      lookback_start_date=lookback_start_date,
      lookback_end_date=lookback_end_date,
  )
  avg_num_builds_per_hour = {
      r['try_builder']: int(math.ceil(float(r['avg_count']))) for r in results
  }

  updated_durations = []
  # Add estimated_bot_hour_cost and avg_num_builds_per_peak_hour
  for r in durations:
    try_builder = r['try_builder']
    shard_count = int(r['shard_count'])

    r['estimated_bot_hour_cost'] = round(
        (r['optimal_shard_count'] - shard_count) *
        (r['test_overhead_min'] / 60) * avg_num_builds_per_hour[try_builder], 2)
    r['avg_num_builds_per_peak_hour'] = avg_num_builds_per_hour[try_builder]
    updated_durations.append(r)
  return updated_durations


def run_query(api, query):

  result = api.step(
      'query', [
          'bq',
          'query',
          f'--project_id={_CLOUD_PROJECT_ID}',
          '--format=json',
          '--max_rows=100000',
          '--nouse_legacy_sql',
          str(query),
      ],
      step_test_data=lambda: api.raw_io.test_api.stream_output_text('[]'),
      stdout=api.json.output())
  result.presentation.logs['query'] = str(query)
  return result.stdout


def _query_avg_num_builds_per_hour(
    api,
    lookback_start_date,
    lookback_end_date,
):
  with api.step.nest('query average builds per hour'):
    query_tmpl = api.file.read_text(
        'read_query',
        api.resource('query_average_number_builds_per_hour.sql.tmpl'))
    query = query_tmpl.format(
        builds_project='cr-buildbucket',
        builds_dataset='chromium',
        lookback_start_date=lookback_start_date,
        lookback_end_date=lookback_end_date,
    )
    return run_query(api, query)


def query_overheads(
    api,
    lookback_start_date,
    lookback_end_date,
):

  with api.step.nest('query overheads'):
    query_tmpl = api.file.read_text(
        'read_query', api.resource('query_test_overheads.sql.tmpl'))
    query = query_tmpl.format(
        builds_project='cr-buildbucket',
        builds_dataset='chromium',
        tasks_project='chromium-swarm',
        tasks_dataset='swarming',
        lookback_start_date=lookback_start_date,
        lookback_end_date=lookback_end_date,
    )
    rows = run_query(api, query)
    trybuilder_to_overheads = {}
    for row in rows:
      sharding = int(row['normally_assigned_shard_count'])
      overhead = (float(row['p50_task_setup_duration_sec']) +
                  float(row['p50_test_harness_overhead_sec'])) / 60
      trybuilder_to_overheads.setdefault(row['try_builder'],
                                         {}).setdefault(row['test_suite'],
                                                        {})[sharding] = overhead
    return trybuilder_to_overheads


def query_durations(
    api,
    target_runtime,
    lookback_start_date,
    lookback_end_date,
):

  def _join_sql_collection(collection):
    return ','.join([f'"{u}"' for u in collection] if collection else '""')

  with api.step.nest('query durations'):
    query_tmpl = api.file.read_text(
        'read_query', api.resource('query_suite_durations.sql.tmpl'))
    query = query_tmpl.format(
        builds_project='cr-buildbucket',
        builds_dataset='chromium',
        tasks_project='chromium-swarm',
        tasks_dataset='swarming',
        lookback_start_date=lookback_start_date,
        lookback_end_date=lookback_end_date,
        percentile=PERCENTILE,
        min_sample_size=MIN_SAMPLE_SIZE,
        target_runtime=target_runtime,
        # TODO(crbug.com/1275620): Replace with
        # service_account.default().get_email()
        ignore_cl_owner=_join_sql_collection([
            'chromium-autosharder@chops-service-accounts.iam.gserviceaccount.com'
        ]),
        exclude_test_suites=_join_sql_collection(TEST_SUITE_EXCLUDE_SET),
        exclude_builders=_join_sql_collection(BUILDER_EXCLUDE_SET),
        exclude_builder_suites=_join_sql_collection([
            f'{builder}:{suite}'
            for builder, suite in BUILDER_TEST_SUITE_EXCLUDE_DICT.items()
        ]),
    )
    return run_query(api, query)


def query_cq_builders(api):
  with api.step.nest('query cq builders'):
    query_tmpl = api.file.read_text('read_query',
                                    api.resource('query_cq_builders.sql.tmpl'))
    query = query_tmpl.format(
        builders_project='chrome-trooper-analytics',
        builders_dataset='metrics',
    )
    rows = run_query(api, query)
    return [row['builder'] for row in rows]


def _prune_builders(api, data):
  cq_builders = query_cq_builders(api)
  data_copy = copy.deepcopy(data)
  for builder_group_name, builder_group in data_copy.items():
    for ci_builder_name, ci_builder in builder_group.items():
      for test_suite_name, test_suite in ci_builder.items():
        try_builder = test_suite['try_builder']
        if try_builder not in cq_builders:
          del data[builder_group_name][ci_builder_name][test_suite_name]
      if len(data[builder_group_name][ci_builder_name]) == 0:
        del data[builder_group_name][ci_builder_name]
    if len(data[builder_group_name]) == 0:
      del data[builder_group_name]


def check_run_conditions(api):
  # If it's a led job, we almost certainly want to run
  if api.led.led_build:
    return None

  # Check if it's been at least 7 days since the last merged reshard CL
  last_merged_change_list = api.gerrit.get_changes(
      name='get last merged change',
      host='https://chromium-review.googlesource.com',
      query_params=[('owner', 'chromium-autosharder'), ('status', 'merged')],
      limit=1,
  )
  # TODO(crbug.com/407846444): We need to verify that comments on CLs don't
  # change the updated timestamp
  if last_merged_change_list:
    last_merged_date = datetime.datetime.strptime(
        last_merged_change_list[0]['updated'],
        '%Y-%m-%d %H:%M:%S.%f000').date()
    current_date = datetime.date.fromtimestamp(api.time.time())
    # Only look up to Monday in order to maintain the same cadence when a CL
    # isn't merged the first time
    start_of_week = current_date - datetime.timedelta(
        days=current_date.weekday())
    if last_merged_date >= start_of_week:
      return result_pb2.RawResult(
          status=common_pb.SUCCESS,
          summary_markdown=(
              'Skipping autosharder CL creation because it has been merged '
              'this week.'),
      )

  # Check to see if there's already an active autosharder CL
  changes = api.gerrit.get_changes(
      name='get active changes',
      host='https://chromium-review.googlesource.com',
      query_params=[('uploader', 'chromium-autosharder'), ('status', 'open')],
  )

  if changes:
    if len(changes) > 1:
      return result_pb2.RawResult(
          status=common_pb.INFRA_FAILURE,
          summary_markdown=(
              'More than one autosharder CL exists. There should only be a max '
              'of one CL at any time.'),
      )

    issue_num = changes[0]['_number']
    with api.context(cwd=api.chromium_checkout.source_dir):
      status_step = api.git_cl(
          'status', ['--issue', issue_num, '--field', 'status'],
          name='git cl status',
          stdout=api.raw_io.output_text(),
          step_test_data=lambda: api.raw_io.test_api.stream_output_text(
              'commit', stream='stdout'))
      cl_status = status_step.stdout.strip()
      status_step.presentation.step_text = cl_status
    # Exit if currently open CL is running a CQ attempt
    if cl_status in ['dry-run', 'commit']:
      return result_pb2.RawResult(
          status=common_pb.SUCCESS,
          summary_markdown=(
              'There is already a CL running a CQ attempt or ready '
              'to submit.'),
      )
    # Close CL so we can upload a new one
    with api.context(cwd=api.chromium_checkout.source_dir):
      api.git_cl('set-close', ['--issue', issue_num], name='git cl set-close')

  return None


def setup_git(api):
  api.git('config', 'user.name', 'autosharder')
  api.git('branch', '-D', 'autoshard', ok_ret='any')
  api.git('restore', '--staged', '.')
  with api.depot_tools.on_path():
    api.git('new-branch', 'autoshard', '--upstream', 'origin/main')


def GenTests(api):
  # Simulate running on a Monday
  current_timestamp = int(datetime.datetime(2023, 7, 3).timestamp())

  autoshard_exceptions_json_path = api.path.cache_dir.joinpath(
      'builder', 'src', 'testing', 'buildbot', 'autoshard_exceptions.json')

  def create_durations_entry(
      waterfall_builder_group,
      waterfall_builder_name,
      try_builder,
      test_suite,
      **kwargs,
  ):
    return {
        'waterfall_builder_group': waterfall_builder_group,
        'waterfall_builder_name': waterfall_builder_name,
        'try_builder': try_builder,
        'test_suite': test_suite,
        'shard_count': 10,
        'p50_pending_time_sec': 1,
        'p90_pending_time_sec': 231,
        'avg_pending_time_sec': 65,
        'avg_task_setup_overhead_sec': 27,
        'percentile_duration_minutes': 20,
        'sample_size': 9508,
        **kwargs,
    }

  def create_overhead_entry(
      waterfall_builder_group,
      waterfall_builder_name,
      try_builder,
      test_suite,
      **kwargs,
  ):
    return {
        'test_suite': test_suite,
        'try_builder': try_builder,
        'waterfall_builder_group': waterfall_builder_group,
        'waterfall_builder_name': waterfall_builder_name,
        'p50_task_setup_duration_sec': 70,
        'p50_test_harness_overhead_sec': 100,
        'normally_assigned_shard_count': 10,
        'experimental_shard_count': 11,
        **kwargs,
    }

  def create_average_builds_per_hour(try_builder, avg_count=80):
    return {
        'try_builder': try_builder,
        'avg_count': avg_count,
    }

  def create_cq_builder(try_builder):
    return {
        'builder': try_builder,
    }

  def boilerplate(durations,
                  overheads,
                  avg_builds_per_hour,
                  cq_builders,
                  current_exceptions=None):

    test_data = [
        api.properties(target_runtime=15.0),
        api.override_step_data(
            'gerrit get last merged change',
            api.json.output([{
                'subject':
                    'Autosharder CL',
                '_number':
                    '12345',
                'updated':
                    datetime.datetime(2023, 7,
                                      1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
            }]),
        ),
        api.path.exists(autoshard_exceptions_json_path),
        api.override_step_data(
            'gerrit get active changes',
            stdout=api.raw_io.output_text(''),
        ),
        api.time.seed(current_timestamp),
    ]

    test_data.append(
        api.override_step_data(
            'read current exceptions file',
            api.file.read_json(
                current_exceptions or {
                    'chromium.builder_group': {
                        'builder_name': {
                            'fake_test_suite': {
                                'try_builder': 'linux-rel',
                                'shards': 4,
                            }
                        }
                    },
                })))

    if durations:
      test_data.append(
          api.override_step_data(
              'query durations.query',
              stdout=api.raw_io.output_text(api.json.dumps(durations))))
    if overheads:
      test_data.append(
          api.override_step_data(
              'query overheads.query',
              stdout=api.raw_io.output_text(api.json.dumps(overheads))))
    if avg_builds_per_hour:
      test_data.append(
          api.override_step_data(
              'query average builds per hour.query',
              stdout=api.raw_io.output_text(
                  api.json.dumps(avg_builds_per_hour))))
    if cq_builders:
      test_data.append(
          api.override_step_data(
              'query cq builders.query',
              stdout=api.raw_io.output_text(api.json.dumps(cq_builders))))
    return sum(test_data, api.empty_test_data())

  def check_exceptions_file_debug(check, steps, builder_group, builder,
                                  test_suite, key, value):
    exceptions_json = api.json.loads(
        steps['write exceptions file'].logs['autoshard_exceptions.json'])
    check(exceptions_json[builder_group][builder][test_suite]['debug'][key] ==
          value)

  def check_exceptions_file(check, steps, builder_group, builder, test_suite,
                            key, value):
    # Checks that the sharding conclusions from the run match the
    # provided sharding values.
    exceptions_json = api.json.loads(
        steps['write exceptions file'].logs['autoshard_exceptions.json'])
    check(exceptions_json[builder_group][builder][test_suite][key] == value)

  def check_sharding(check, steps, builder_group, builder, test_suite,
                     sharding):
    check_exceptions_file(check, steps, builder_group, builder, test_suite,
                          'shards', sharding)

  def check_not_sharded(check, steps, builder_group):
    exceptions_json = api.json.loads(
        steps['write exceptions file'].logs['autoshard_exceptions.json'])

    check(builder_group not in exceptions_json)

  yield api.test(
      'basic',
      boilerplate(
          durations=[
              create_durations_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
              )
          ],
          overheads=[
              create_overhead_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
              )
          ],
          avg_builds_per_hour=[
              create_average_builds_per_hour(try_builder='linux-rel'),
          ],
          cq_builders=[
              create_cq_builder(try_builder='linux-rel'),
          ],
      ),
      api.post_process(post_process.MustRun, 'query durations'),
      api.post_process(post_process.MustRun, 'regenerate targets specs'),
      api.post_process(post_process.MustRun, 'git cl upload'),
      api.post_process(check_sharding, 'chromium.linux', 'Linux Tests',
                       'browser_tests', 15),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'dont_shard_to_1',
      boilerplate(
          durations=[
              create_durations_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
                  percentile_duration_minutes=5,
                  shard_count=2,
              )
          ],
          overheads=[
              create_overhead_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
                  normally_assigned_shard_count=2,
                  experimental_shard_count=3,
                  p50_test_harness_overhead_sec=1,
              )
          ],
          avg_builds_per_hour=[
              create_average_builds_per_hour(try_builder='linux-rel'),
          ],
          cq_builders=[
              create_cq_builder(try_builder='linux-rel'),
          ],
          current_exceptions={
              'chromium.linux': {
                  'Linux Tests': {
                      'browser_tests': {
                          'shards': 2,
                          'try_builder': 'linux-rel',
                      }
                  }
              }
          }),
      api.post_process(post_process.MustRun, 'query durations'),
      api.post_process(post_process.MustRun, 'regenerate targets specs'),
      api.post_process(post_process.MustRun, 'git cl upload'),
      api.post_process(check_sharding, 'chromium.linux', 'Linux Tests',
                       'browser_tests', 2),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'old_shard_in_loopback',
      boilerplate(
          durations=[
              create_durations_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
                  shard_count=10,
              ),
              # This should be ignored because it is picking it up from
              # a previous sharding. Not the latest
              create_durations_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
                  percentile_duration_minutes=1000,
                  shard_count=5,
              ),
          ],
          overheads=[
              create_overhead_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
                  normally_assigned_shard_count=10,
                  experimental_shard_count=11,
              ),
              create_overhead_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
                  normally_assigned_shard_count=5,
                  experimental_shard_count=6,
              ),
          ],
          avg_builds_per_hour=[
              create_average_builds_per_hour(try_builder='linux-rel'),
          ],
          cq_builders=[
              create_cq_builder(try_builder='linux-rel'),
          ],
          current_exceptions={
              'chromium.linux': {
                  'Linux Tests': {
                      'browser_tests': {
                          'shards': 10,
                          'try_builder': 'linux-rel',
                      }
                  }
              }
          }),
      api.post_process(post_process.MustRun, 'query durations'),
      api.post_process(post_process.MustRun, 'regenerate targets specs'),
      api.post_process(post_process.MustRun, 'git cl upload'),
      api.post_process(check_sharding, 'chromium.linux', 'Linux Tests',
                       'browser_tests', 15),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'optimal_shards_less_than_zero',
      boilerplate(
          durations=[
              create_durations_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
                  percentile_duration_minutes=3.0,
              ),
          ],
          overheads=[
              create_overhead_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
                  p50_test_harness_overhead_sec=60 * 4),
          ],
          avg_builds_per_hour=[
              create_average_builds_per_hour(try_builder='linux-rel'),
          ],
          cq_builders=[
              create_cq_builder(try_builder='linux-rel'),
          ],
      ),
      api.post_process(post_process.MustRun, 'query durations'),
      api.post_process(post_process.MustRun, 'regenerate targets specs'),
      api.post_process(post_process.MustRun, 'git cl upload'),
      api.post_process(check_not_sharded, 'chromium.linux'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'test_multiple_builders_in_group',
      boilerplate(
          durations=[
              create_durations_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
              ),
              create_durations_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux GPU Tests',
                  try_builder='linux-rel',
                  test_suite='gpu_tests',
                  shard_count=10,
                  percentile_duration_minutes=30,
              ),
          ],
          overheads=[
              create_overhead_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
              ),
              create_overhead_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux GPU Tests',
                  try_builder='linux-rel',
                  test_suite='gpu_tests',
              ),
          ],
          avg_builds_per_hour=[
              create_average_builds_per_hour(try_builder='linux-rel'),
          ],
          cq_builders=[
              create_cq_builder(try_builder='linux-rel'),
          ],
      ),
      api.post_process(check_sharding, 'chromium.linux', 'Linux Tests',
                       'browser_tests', 15),
      api.post_process(check_sharding, 'chromium.linux', 'Linux GPU Tests',
                       'gpu_tests', 23),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'test_merge_existing_output_file',
      boilerplate(
          durations=[
              create_durations_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
                  percentile_duration_minutes=30,
                  shard_count=10,
              ),
          ],
          overheads=[
              create_overhead_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
              ),
          ],
          avg_builds_per_hour=[
              create_average_builds_per_hour(try_builder='linux-rel'),
          ],
          cq_builders=[
              create_cq_builder(try_builder='linux-rel'),
              create_cq_builder(try_builder='android-try'),
          ],
          current_exceptions={
              'chromium.linux': {
                  'Linux Tests': {
                      'browser_tests': {
                          'shards': 10,
                          'try_builder': 'linux-rel',
                      },
                      'interactive_ui_tests': {
                          'shards': 3,
                          'try_builder': 'linux-rel',
                      }
                  },
              },
              'chromium.android': {
                  'android-12-x64-rel': {
                      'webview_instrumentation_test_apk': {
                          'shards': 11,
                          'try_builder': 'android-try',
                      }
                  }
              }
          }),
      api.post_process(check_sharding, 'chromium.linux', 'Linux Tests',
                       'browser_tests', 23),
      api.post_process(check_sharding, 'chromium.linux', 'Linux Tests',
                       'interactive_ui_tests', 3),
      api.post_process(check_sharding, 'chromium.android', 'android-12-x64-rel',
                       'webview_instrumentation_test_apk', 11),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'test_reduce_shards_already_autosharded',
      boilerplate(
          durations=[
              create_durations_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
                  percentile_duration_minutes=10,
                  shard_count=15,
              ),
          ],
          overheads=[
              create_overhead_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
              ),
          ],
          avg_builds_per_hour=[
              create_average_builds_per_hour(try_builder='linux-rel'),
          ],
          cq_builders=[
              create_cq_builder(try_builder='linux-rel'),
              create_cq_builder(try_builder='android-try'),
          ],
          current_exceptions={
              'chromium.linux': {
                  'Linux Tests': {
                      'browser_tests': {
                          'shards': 15,
                          'try_builder': 'linux-rel',
                      },
                      'interactive_ui_tests': {
                          'shards': 3,
                          'try_builder': 'linux-rel',
                      }
                  },
              },
              'chromium.android': {
                  'android-12-x64-rel': {
                      'webview_instrumentation_test_apk': {
                          'shards': 11,
                          'try_builder': 'android-try',
                      }
                  }
              }
          }),
      api.post_process(check_sharding, 'chromium.linux', 'Linux Tests',
                       'browser_tests', 10),
      api.post_process(check_sharding, 'chromium.linux', 'Linux Tests',
                       'interactive_ui_tests', 3),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'test_multiple_overhead_values',
      boilerplate(
          durations=[
              create_durations_entry(
                  waterfall_builder_group='chromium.android',
                  waterfall_builder_name='android-12-x64-rel',
                  try_builder='android-12-x64-rel',
                  test_suite='webview_instrumentation_test_apk',
                  shard_count=20,
                  percentile_duration_minutes=20,
              ),
          ],
          overheads=[
              create_overhead_entry(
                  waterfall_builder_group='chromium.android',
                  waterfall_builder_name='android-12-x64-rel',
                  try_builder='android-12-x64-rel',
                  test_suite='webview_instrumentation_test_apk',
                  normally_assigned_shard_count=19,
                  experimental_shard_count=20,
                  p50_task_setup_duration_sec=30,
                  p50_test_harness_overhead_sec=60,
              ),
              create_overhead_entry(
                  waterfall_builder_group='chromium.android',
                  waterfall_builder_name='android-12-x64-rel',
                  try_builder='android-12-x64-rel',
                  test_suite='webview_instrumentation_test_apk',
                  normally_assigned_shard_count=20,
                  experimental_shard_count=21,
                  p50_task_setup_duration_sec=30,
                  p50_test_harness_overhead_sec=120,
              ),
          ],
          avg_builds_per_hour=[
              create_average_builds_per_hour(try_builder='android-12-x64-rel'),
          ],
          cq_builders=[
              create_cq_builder(try_builder='android-12-x64-rel'),
          ]),
      api.post_process(check_exceptions_file_debug, 'chromium.android',
                       'android-12-x64-rel', 'webview_instrumentation_test_apk',
                       'test_overhead_min', 2.5),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'test_reject_suggested_decrease_if_percentile_min_was_close_to_desired',
      boilerplate(
          durations=[
              create_durations_entry(
                  waterfall_builder_group='chromium.android',
                  waterfall_builder_name='android-12-x64-rel',
                  try_builder='android-12-x64-rel',
                  test_suite='webview_instrumentation_test_apk',
                  shard_count=10,
                  percentile_duration_minutes=14.5,
              ),
          ],
          overheads=[
              create_overhead_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
              ),
          ],
          avg_builds_per_hour=[
              create_average_builds_per_hour(try_builder='android-12-x64-rel'),
          ],
          cq_builders=[
              create_cq_builder(try_builder='android-12-x64-rel'),
          ],
          current_exceptions={
              'chromium.android': {
                  'android-12-x64-rel': {
                      'webview_instrumentation_test_apk': {
                          'shards': 10,
                          'try_builder': 'android-12-x64-rel',
                      }
                  }
              }
          }),
      api.post_process(check_sharding, 'chromium.android', 'android-12-x64-rel',
                       'webview_instrumentation_test_apk', 10),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'test_reject_suggested_decrease_if_simulated_is_too_high',
      boilerplate(
          durations=[
              create_durations_entry(
                  waterfall_builder_group='chromium.android',
                  waterfall_builder_name='android-12-x64-rel',
                  try_builder='android-12-x64-rel',
                  test_suite='webview_instrumentation_test_apk',
                  shard_count=10,
                  percentile_duration_minutes=14,
              ),
          ],
          overheads=[
              create_overhead_entry(
                  waterfall_builder_group='chromium.linux',
                  waterfall_builder_name='Linux Tests',
                  try_builder='linux-rel',
                  test_suite='browser_tests',
              ),
          ],
          avg_builds_per_hour=[
              create_average_builds_per_hour(try_builder='android-12-x64-rel'),
          ],
          cq_builders=[
              create_cq_builder(try_builder='android-12-x64-rel'),
          ],
          current_exceptions={
              'chromium.android': {
                  'android-12-x64-rel': {
                      'webview_instrumentation_test_apk': {
                          'shards': 10,
                          'try_builder': 'android-12-x64-rel',
                      }
                  }
              }
          }),
      api.post_process(check_sharding, 'chromium.android', 'android-12-x64-rel',
                       'webview_instrumentation_test_apk', 10),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'test_not_already_autosharded_decrease',
      boilerplate(
          durations=[
              create_durations_entry(
                  waterfall_builder_group='chromium.android',
                  waterfall_builder_name='android-12-x64-rel',
                  try_builder='android-12-x64-rel',
                  test_suite='webview_instrumentation_test_apk',
                  shard_count=10,
                  percentile_duration_minutes=9,
              ),
          ],
          overheads=[
              create_overhead_entry(
                  waterfall_builder_group='chromium.android',
                  waterfall_builder_name='android-12-x64-rel',
                  try_builder='android-12-x64-rel',
                  test_suite='webview_instrumentation_test_apk',
              ),
          ],
          avg_builds_per_hour=[
              create_average_builds_per_hour(try_builder='android-12-x64-rel'),
              create_average_builds_per_hour(try_builder='linux-rel'),
          ],
          cq_builders=[
              create_cq_builder(try_builder='android-12-x64-rel'),
              create_cq_builder(try_builder='linux-rel'),
          ],
          current_exceptions={
              'chromium.linux': {
                  'Linux Tests': {
                      'browser_tests': {
                          'shards': 10,
                          'try_builder': 'linux-rel',
                      }
                  }
              },
          }),
      api.post_process(check_not_sharded, 'chromium.android'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'test_not_already_autosharded_increase',
      boilerplate(
          durations=[
              create_durations_entry(
                  waterfall_builder_group='chromium.android',
                  waterfall_builder_name='android-12-x64-rel',
                  try_builder='android-12-x64-rel',
                  test_suite='webview_instrumentation_test_apk',
                  shard_count=10,
                  percentile_duration_minutes=20,
              ),
          ],
          overheads=[
              create_overhead_entry(
                  waterfall_builder_group='chromium.android',
                  waterfall_builder_name='android-12-x64-rel',
                  try_builder='android-12-x64-rel',
                  test_suite='webview_instrumentation_test_apk',
              ),
          ],
          avg_builds_per_hour=[
              create_average_builds_per_hour(try_builder='android-12-x64-rel'),
              create_average_builds_per_hour(try_builder='linux-rel'),
          ],
          cq_builders=[
              create_cq_builder(try_builder='android-12-x64-rel'),
              create_cq_builder(try_builder='linux-rel'),
          ],
          current_exceptions={
              'chromium.linux': {
                  'Linux Tests': {
                      'browser_tests': {
                          'shards': 10,
                          'try_builder': 'linux-rel',
                      }
                  }
              },
          }),
      api.post_process(check_sharding, 'chromium.android', 'android-12-x64-rel',
                       'webview_instrumentation_test_apk', 15),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'test_pruned',
      boilerplate(
          durations=[
              create_durations_entry(
                  waterfall_builder_group='chromium.win',
                  waterfall_builder_name='Win10 Tests x64',
                  try_builder='win-rel',
                  test_suite='browser_tests',
              ),
          ],
          overheads=[
              create_overhead_entry(
                  waterfall_builder_group='chromium.win',
                  waterfall_builder_name='Win10 Tests x64',
                  try_builder='win-rel',
                  test_suite='browser_tests',
              ),
          ],
          avg_builds_per_hour=[
              create_average_builds_per_hour(try_builder='win-rel'),
          ],
          cq_builders=[
              create_cq_builder(try_builder='linux-rel'),
          ],
          current_exceptions={
              'chromium.linux': {
                  'Linux Tests': {
                      'browser_tests': {
                          'shards': 10,
                          'try_builder': 'linux-rel',
                      }
                  }
              },
              'chromium.win': {
                  'Win Tests': {
                      'browser_tests': {
                          'shards': 10,
                          'try_builder': 'win-rel',
                      }
                  }
              },
          }),
      api.post_process(check_not_sharded, 'chromium.win'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'led_job',
      api.properties(**{
          '$recipe_engine/led': {
              'shadowed_bucket': 'try',
          },
      }),
      api.time.seed(current_timestamp),
      api.path.exists(autoshard_exceptions_json_path),
      api.override_step_data(
          'git diff',
          stdout=api.raw_io.output_text(''),
      ),
      api.post_process(post_process.MustRun, 'query durations'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'no_change',
      api.time.seed(current_timestamp),
      api.path.exists(autoshard_exceptions_json_path),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          stdout=api.raw_io.output_text(''),
      ),
      api.override_step_data(
          'git diff',
          stdout=api.raw_io.output_text(''),
      ),
      api.post_process(post_process.MustRun, 'query durations'),
      api.post_process(post_process.DoesNotRun, 'regenerate targets specs'),
      api.post_process(post_process.DoesNotRun, 'git cl upload'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'already merged this week',
      api.time.seed(current_timestamp),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    3).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.post_process(
          post_process.SummaryMarkdown,
          'Skipping autosharder CL creation because it has been merged '
          'this week.'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'too_many_existing_cls',
      api.time.seed(current_timestamp),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          api.json.output([{
              'subject': 'Autosharder CL',
              '_number': '12346',
          }, {
              'subject': 'Autosharder CL',
              '_number': '12347'
          }]),
      ),
      api.post_process(post_process.DoesNotRun, 'query durations'),
      api.post_process(post_process.DoesNotRun, 'regenerate targets specs'),
      api.post_process(post_process.DoesNotRun, 'git cl set-close'),
      api.post_process(post_process.DoesNotRun, 'git cl upload'),
      api.expect_status('INFRA_FAILURE'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'no_existing_cl',
      api.time.seed(current_timestamp),
      api.path.exists(autoshard_exceptions_json_path),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          stdout=api.raw_io.output_text(''),
      ),
      api.post_process(post_process.MustRun, 'query durations'),
      api.post_process(post_process.MustRun, 'regenerate targets specs'),
      api.post_process(post_process.DoesNotRun, 'git cl set-close'),
      api.post_process(post_process.MustRun, 'git cl upload'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'no_landed_CL_yet',
      api.time.seed(current_timestamp),
      api.override_step_data(
          'gerrit get last merged change',
          stdout=api.raw_io.output_text(''),
      ),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'current_dry_run',
      api.time.seed(current_timestamp),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          api.json.output([{
              'subject': 'Autosharder CL',
              '_number': '12346',
          }]),
      ),
      api.override_step_data(
          'git cl status',
          stdout=api.raw_io.output_text('dry-run'),
      ),
      api.post_process(post_process.DoesNotRun, 'query durations'),
      api.post_process(post_process.DoesNotRun, 'regenerate targets specs'),
      api.post_process(post_process.DoesNotRun, 'git cl set-close'),
      api.post_process(post_process.DoesNotRun, 'git cl upload'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'existing_waiting_cl',
      api.time.seed(current_timestamp),
      api.path.exists(autoshard_exceptions_json_path),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          api.json.output([{
              'subject': 'Autosharder CL',
              '_number': '12346',
          }]),
      ),
      api.override_step_data(
          'git cl status',
          stdout=api.raw_io.output_text('waiting'),
      ),
      api.post_process(post_process.MustRun, 'git cl set-close'),
      api.post_process(post_process.MustRun, 'query durations'),
      api.post_process(post_process.MustRun, 'regenerate targets specs'),
      api.post_process(post_process.MustRun, 'git cl upload'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'new autoshard exceptions path',
      api.time.seed(current_timestamp),
      api.path.exists(
          api.path.cache_dir.joinpath('builder', 'src', 'infra', 'config',
                                      'targets', 'autoshard_exceptions.json')),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          stdout=api.raw_io.output_text(''),
      ),
      api.override_step_data(
          'git diff',
          stdout=api.raw_io.output_text(''),
      ),
      api.post_process(post_process.MustRun, 'query durations'),
      api.post_process(post_process.DoesNotRun, 'regenerate targets specs'),
      api.post_process(post_process.DoesNotRun, 'git cl upload'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'no autoshard exceptions',
      api.time.seed(current_timestamp),
      api.override_step_data(
          'gerrit get last merged change',
          api.json.output([{
              'subject':
                  'Autosharder CL',
              '_number':
                  '12345',
              'updated':
                  datetime.datetime(2023, 7,
                                    1).strftime('%Y-%m-%d %H:%M:%S.%f000'),
          }]),
      ),
      api.override_step_data(
          'gerrit get active changes',
          stdout=api.raw_io.output_text(''),
      ),
      api.expect_status('INFRA_FAILURE'),
      api.post_process(post_process.MustRun,
                       'autoshard exceptions file not found'),
      api.post_process(post_process.DropExpectation),
  )
