// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.build.chromium.fuzz;

// Next ID: 11
message InputProperties {
  string archive_prefix = 1;

  // Path prefix to use verbatim for the uploaded zip archive.
  // If `use_archive_path` is true, this path is used verbatim.
  // Otherwise, the derived path is checked to match this path.
  string archive_path = 9;

  // If true, use `archive_path` verbatim and skip path derivation.
  bool use_archive_path = 10;

  bool v8_targets_only = 2;
  bool ios_targets_only = 3;
  string upload_bucket = 4;
  string upload_directory = 5;
  bool collect_fuzz_coverage = 6;
  string fuzz_engine = 7;
  // Optional Version number to control how libfuzzer archives are formatted.
  // 0: Legacy with src_root archiving where archive root is build dir
  // 1: New archive schema where archive root is source dir
  // If not set, fuzz.py will use its `DEFAULT_ARCHIVE_SCHEMA_VERSION` as
  // the value of archive_schema_version.
  optional uint32 archive_schema_version = 8;
}
