// Copyright 2022 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.build.chromium.targets_config_verifier;

// Next ID: 2
message InputProperties {

  // Required, the directory where the per-builder config files are located
  //
  // The path is relative to the root of the repo. For each builder, the
  // relative path to the test files from the builder config directory must be
  // <bucket>/<builder>/targets/*.json. The corresponding builders must be
  // bootstrapped, with the builder config specified src-side. For each builder,
  // the relative path to the properties file from the builder config directory
  // must be <bucket>/<builder>/properties.json.
  string builder_config_directory = 1;

  // Buckets where the targets config should be created for precommit
  //
  // The bucket for a targets config will be computed based on the path to the
  // test files (see the description of builder_config_directory). For a builder
  // with a bucket in precommit_buckets, the targets config will be generated
  // using the pre-commit-specific behavior (e.g. generated test specs will
  // include precommit_args instead of non_precommit_args).
  repeated string precommit_buckets = 2;
}
