// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.build.chromium.universal_test_runner;

// Next ID: 10
message InputProperties {
  // Required, the directory where chromium is checked out not including the src
  // dir
  string checkout_path = 1;

  // Test names to run
  //
  // This must match the test names, not their target names to uniquely identify
  // the tests to be run on the builder
  repeated string test_names = 2;

  // Optional map of revisions received during gclient sync
  map<string, string> got_revisions = 3;

  // The build_dir to use either containing the binary to run or where it is to
  // be compiled
  string build_dir = 4;

  enum RunType {
    RUN_TYPE_RUN = 0;
    RUN_TYPE_COMPILE = 1;
    RUN_TYPE_COMPILE_AND_RUN = 2;
  }

  // Whether or not the recipe should attempt to build and/or build the tests
  RunType run_type = 5;

  // When true the gn args in the build dir will be preserved. Otherwise
  // the builder gn args will overwrite the file
  bool preserve_gn_args = 6;

  // When true code coverage is skipped
  bool disable_code_coverage = 7;

  // Where to write properties for the next potential run. A json representation
  // of this proto will be written to output_properties_file if the recipe
  // determines a rerun with new properties can be run.
  string output_properties_file = 8;

  // Skip checking .gclient mismatches
  bool bypass_gclient = 9;
}
