// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.build.chromium.universal_test_runner;

// Next ID: 8
message InputProperties {
  // Required, the directory where chromium is checked out not including the src
  // dir
  string checkout_path = 1;

  // Test names to run
  //
  // This must match the test names, not their target names to uniquely identify
  // the tests to be run on the builder
  repeated string test_names = 2;

  // The build_dir to use either containing the binary to run or where it is to
  // be compiled
  string build_dir = 3;

  enum RunType {
    RUN_TYPE_RUN = 0;
    RUN_TYPE_COMPILE = 1;
    RUN_TYPE_COMPILE_AND_RUN = 2;
  }

  // Whether or not the recipe should attempt to build and/or build the tests
  RunType run_type = 4;

  // Where to write properties for the next potential runs. Each options will
  // be a string representing what the user should see mapped to alterations
  // to this input proto that should be used for the next run when selected.
  // An empty set of proto implies there is not change and no reason to rerun
  // and should instead abort.
  // The first option should be the default to use as well as the option to use
  // when a --forced run is desired.
  string output_properties_file = 5;

  // Next ID: 6
  message RerunOptions {
    // Skip checking .gclient mismatches
    bool bypass_gclient = 1;

    // Skip checking gn arg mismatches
    bool bypass_gn_args = 2;

    // When true the gn args in the build dir will be preserved. Otherwise
    // the builder gn args will overwrite the file. If code coverage is active
    // and the user chooses to instrument everything, the
    // coverage_instrumentation_input_file arg will still be removed
    bool preserve_gn_args = 3;

    // Skip checking for an upstream branch
    bool bypass_branch_check = 4;

    // How to proceed if the bypass_branch_check is bypassed
    bool skip_instrumentation = 5;
  }

  // The recipe being run by the builder. The 'recipe' input property gets
  // overwritten by the recipe so this property needs to provide this info
  string builder_recipe = 6;

  // Options that are used to re-invoke the recipe
  RerunOptions rerun_options = 7;
}
