// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.build.v8.release_branch_updater;

message InputProperties {
  // Channels to be updated.
  repeated ChannelProperties channels = 1;
}

message ChannelProperties {
  // Ref refs/heads/<refname> in the v8 repository to be updated.
  string refname = 1;

  // Weeks until the branch should be updated. Otherwise, the builder fails.
  float max_age_weeks = 2;

  // Set the name of the channel at the source.
  string source_channel = 3;
}
