# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import annotations

import functools

from recipe_engine import recipe_api
from recipe_engine.config_types import Path
from RECIPE_MODULES.build import chromium_swarming
from RECIPE_MODULES.depot_tools.bot_update.api import Result


class PinlistApi(recipe_api.RecipeApi):

  def __init__(self, properties, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self._upload_pinlist = properties.upload_pinlist

  @functools.cached_property
  def pinlist_dir(self) -> Path:
    """The directory containing the generated pinlist."""
    return self.m.path.mkdtemp()

  @property
  def upload_pinlist(self):
    """Indicates the generated pinlist should be uploaded to CIPD.

    Used by chromium_tests.run_tests() to trigger the upload logic.
    """
    return self._upload_pinlist

  @property
  def _branch(self):
    """Parse the branch name from ref."""
    ref = self.m.buildbucket.gitiles_commit.ref
    if not ref:
      raise self.m.step.StepFailure(
          f'Missing ref: {self.m.buildbucket.gitiles_commit}')
    # Release ref: refs/branch-heads/4103
    # Main ref: refs/heads/main
    return ref.split('/', 2)[2]

  def _get_arch(self):
    """Return the architecture name used for the pinlist artifact."""
    if (self.m.chromium.c.TARGET_ARCH == 'arm' and
        self.m.chromium.c.TARGET_BITS == 64):
      return 'arm64'
    raise self.m.step.StepFailure(
        f'Unsupported arch={self.m.chromium.c.TARGET_ARCH} '
        f'bits={self.m.chromium.c.TARGET_BITS}. '
        'Currently only arm64 is supported.')

  def _get_pinlist_package_name(self, arch, builder_name):
    """Returns the CIPD package name for the pinlist."""
    if 'webview' in builder_name:
      return f'chromium/android_webview/tools/pinlist/{arch}'
    raise self.m.step.StepFailure(
        f'Unimplemented builder: {builder_name}. '
        'Currently only Webview builders are supported for pinlist generation.')

  def process_pinlist_data(self, result: Result):
    """Processes the pinlist generated by the benchmarks.

    Args:
      result: The bot_update result from the build.
    """

    with self.m.step.nest('processing generated pinlist') as presentation:
      pinlist_dir = self.pinlist_dir
      arch = self._get_arch()
      pinlist_name = 'pinlist.meta'
      pinlist_path = pinlist_dir / pinlist_name
      presentation.step_text += arch + '<br/>'
      presentation.step_text += pinlist_name + '<br/>'
      presentation.step_text += str(pinlist_path) + '<br/>'
      if not self.m.path.exists(pinlist_path):
        presentation.status = self.m.step.FAILURE
        raise self.m.step.StepFailure(f'Pinlist not found at {pinlist_path}')

      if not self.upload_pinlist:
        return self.m.step.empty(
            'skipping upload to CIPD for this generated pinlist as the '
            'upload_pinlist property is not enabled')

      pkg_def = self.m.cipd.PackageDefinition(
          package_name=self._get_pinlist_package_name(
              arch, self.m.buildbucket.builder_name),
          package_root=pinlist_dir,
      )

      if not self.m.led.led_build:
        self.m.bcid_reporter.report_stage('start')

      pkg_def.add_file(pinlist_path)

      revision = result.manifest['src']['revision']
      tags = {
          'git_revision': revision,
          'branch': self._branch,
      }
      if not self.m.led.led_build:
        self.m.bcid_reporter.create_from_pkg(
            pkg_def, tags=tags, refs=[f'latest-{self._branch}'])

        self.m.bcid_reporter.report_stage('upload-complete')

  def shard_merge(self):
    """Returns a MergeScript for merging swarming shards for pinlist generation."""
    return chromium_swarming.MergeScript(
        script=self.m.chromium_checkout.source_dir /
        'testing/merge_scripts/pinlist_noop_merge.py',
        args=['--pinlist-dir', self.pinlist_dir])
