# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import annotations

from recipe_engine.post_process import (
  DoesNotRunRE,
  DropExpectation,
  SummaryMarkdown,
)

from dataclasses import dataclass

from recipe_engine.recipe_api import RecipeScriptApi
from recipe_engine.recipe_test_api import RecipeTestApi

from RECIPE_MODULES.build import v8, v8_auto_roller
from RECIPE_MODULES.recipe_engine import (
  buildbucket,
  cipd,
  context,
  file,
  json,
  path,
  properties,
  raw_io,
  step,
)


@dataclass
class DEPS(RecipeScriptApi):
  buildbucket: buildbucket.API
  cipd: cipd.API
  context: context.API
  file: file.API
  json: json.API
  path: path.API
  properties: properties.API
  raw_io: raw_io.API
  step: step.API
  v8: v8.API
  v8_auto_roller: v8_auto_roller.API


@dataclass
class TEST_DEPS(RecipeTestApi):
  json: json.TEST_API
  properties: properties.TEST_API
  raw_io: raw_io.TEST_API
  v8: v8.TEST_API


RETSAM = 'retsam'[::-1]


def RunSteps(api: DEPS):
  """This tests the CL manager using a dummy roller."""

  update_result = api.v8_auto_roller.setup_target(
    'dummy',
    'https://chromium.googlesource.com/dumb/dumber',
  )
  source_dir = update_result.source_root.path

  clm = api.v8_auto_roller.build_cl_manager(
    source_dir, bugs='dummy:123', cc="nobody"
  )

  api.v8_auto_roller.dummy_roll(clm, source_dir)
  if api.properties.get('try_again', False):
    api.v8_auto_roller.dummy_roll(clm, source_dir)

  return api.v8_auto_roller.report_result()


def GenTests(api: TEST_DEPS):

  def test(name):
    return (
      (api.test(name))
      + api.override_step_data(
        'Update dummy deps.gerrit changes',
        api.json.output([{'_number': '123', 'subject': 'dummy'}]),
      )
      + api.override_step_data(
        'Update dummy deps.git status',
        api.raw_io.stream_output_text(
          'diff generated by script', stream='stdout'
        ),
      )
      + api.override_step_data(
        'Update dummy deps.git cl',
        api.raw_io.stream_output_text(
          "https://chromium-review.googlesource.com/"
          "c/chromium/tools/build/+/3840339",
          stream='stdout',
        ),
      )
    )

  yield test('default') + api.override_step_data(
    'Update dummy deps.git status',
    api.raw_io.stream_output_text('diff generated by roller', stream='stdout'),
  )

  def runs_only(api: TEST_DEPS, *step_names):
    """Only include steps from the expectations."""
    return api.post_process(
      DoesNotRunRE, api.v8.exclude_by_names_re(*step_names)
    )

  yield (
    api.test('no-diff')
    + runs_only(
      api,
      "Setup",
      "Setup.ensure builder cache dir",
      "Setup.bot_update",
      "Update dummy deps",
      "Update dummy deps.get login info",
      "Update dummy deps.gerrit changes",
      "Update dummy deps.git checkout",
      "Update dummy deps.git branch",
      "Update dummy deps.git clean",
      "Update dummy deps.git new-branch",
      "Update dummy deps.git status",
      "$result",
    )
    + api.post_process(DropExpectation)
  )

  yield (
    api.test('failure')
    + api.properties(u_no_pass=True, try_again=True)
    + runs_only(
      api,
      "Setup",
      "Setup.ensure builder cache dir",
      "Setup.bot_update",
      "Update dummy deps",
      "Update dummy deps.get login info",
      "Update dummy deps.gerrit changes",
      "Update dummy deps.git checkout",
      "Update dummy deps.git branch",
      "Update dummy deps.git clean",
      "Update dummy deps.git new-branch",
      "Update dummy deps.Roll failed",
      "Update dummy deps (2)",
      "Update dummy deps (2).get login info",
      "Update dummy deps (2).gerrit changes",
      "Update dummy deps (2).git checkout",
      "Update dummy deps (2).git branch",
      "Update dummy deps (2).git clean",
      "Update dummy deps (2).git new-branch",
      "Update dummy deps (2).Roll failed",
      "$result",
    )
    + api.expect_status('FAILURE')
    + api.post_process(SummaryMarkdown, "Failed to update dummy, dummy.")
    + api.post_process(DropExpectation)
  )
