# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import annotations

from recipe_engine.post_process import (DoesNotRunRE, DropExpectation,
                                        SummaryMarkdown)

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/cipd',
    'recipe_engine/context',
    'recipe_engine/file',
    'recipe_engine/json',
    'recipe_engine/path',
    'recipe_engine/properties',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'v8',
    'v8_auto_roller',
]

RETSAM = 'retsam'[::-1]


def RunSteps(api):
  """This tests the CL manager using a dummy roller."""

  update_result = api.v8_auto_roller.setup_target(
      'dummy',
      'https://chromium.googlesource.com/dumb/dumber',
  )
  source_dir = update_result.source_root.path

  clm = api.v8_auto_roller.build_cl_manager(
      source_dir, bugs='dummy:123', cc="nobody")

  api.v8_auto_roller.dummy_roll(clm, source_dir)
  if api.properties.get('try_again', False):
    api.v8_auto_roller.dummy_roll(clm, source_dir)

  return api.v8_auto_roller.report_result()


def GenTests(api):

  def test(name):
    return (api.test(name)) + api.override_step_data(
        'Update dummy deps.gerrit changes',
        api.json.output([{
            '_number': '123',
            'subject': 'dummy'
        }]),
    ) + api.override_step_data(
        'Update dummy deps.git status',
        api.raw_io.stream_output_text(
            'diff generated by script', stream='stdout'),
    ) + api.override_step_data(
        'Update dummy deps.git cl',
        api.raw_io.stream_output_text(
            "https://chromium-review.googlesource.com/"
            "c/chromium/tools/build/+/3840339",
            stream='stdout'),
    )

  yield test('default') + api.override_step_data(
      'Update dummy deps.git status',
      api.raw_io.stream_output_text(
          'diff generated by roller', stream='stdout'),
  )

  def runs_only(api, *step_names):
    """Only include steps from the expectations."""
    return api.post_process(DoesNotRunRE,
                            api.v8.exclude_by_names_re(*step_names))

  yield api.test('no-diff') + runs_only(
      api,
      "Setup",
      "Setup.ensure builder cache dir",
      "Setup.bot_update",
      "Update dummy deps",
      "Update dummy deps.get login info",
      "Update dummy deps.gerrit changes",
      "Update dummy deps.git checkout",
      "Update dummy deps.git branch",
      "Update dummy deps.git clean",
      "Update dummy deps.git new-branch",
      "Update dummy deps.git status",
      "$result",
  ) + api.post_process(DropExpectation)

  yield (api.test('failure') + api.properties(u_no_pass=True, try_again=True) +
         runs_only(
             api,
             "Setup",
             "Setup.ensure builder cache dir",
             "Setup.bot_update",
             "Update dummy deps",
             "Update dummy deps.get login info",
             "Update dummy deps.gerrit changes",
             "Update dummy deps.git checkout",
             "Update dummy deps.git branch",
             "Update dummy deps.git clean",
             "Update dummy deps.git new-branch",
             "Update dummy deps.Roll failed",
             "Update dummy deps (2)",
             "Update dummy deps (2).get login info",
             "Update dummy deps (2).gerrit changes",
             "Update dummy deps (2).git checkout",
             "Update dummy deps (2).git branch",
             "Update dummy deps (2).git clean",
             "Update dummy deps (2).git new-branch",
             "Update dummy deps (2).Roll failed",
             "$result",
         ) + api.expect_status('FAILURE') +
         api.post_process(SummaryMarkdown, "Failed to update dummy, dummy.") +
         api.post_process(DropExpectation))
