// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";
package recipes.build.android.sdk_packager;

message SdkCipdPackage {
  // Name of the SDK package to create as reported by sdkmanager.
  string sdk_package_name = 1;
  // Path to the yaml file relative to chromium/src.
  string cipd_yaml = 2;
  // Release channel to check. Default to STABLE if not present.
  optional SdkChannel sdk_channel = 3;
  // Target OS that is different from the host machine.
  optional TargetOs target_os = 4;
  // Target arch that is different from the host machine.
  optional TargetArch target_arch = 5;
}

enum SdkChannel {
  STABLE = 0;  // default value
  BETA = 1;
  DEV = 2;
  CANARY = 3;
}

// The target OS for a package.
// See https://developer.android.com/tools/variables#repo_os_override for more.
enum TargetOs {
  linux = 0;  // default value
  mac = 1;
  windows = 2;
}

// The target arch for a package.
enum TargetArch {
  x86_64 = 0;  // default value
  arm64 = 1;
}

message InputProperties {
  // CIPD packages to create from Android SDK packages.
  repeated SdkCipdPackage packages = 1;
}
