// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
syntax = "proto3";

package recipes.build.branch_configuration.tester;

message BranchConfig {
  // Next ID: 7

  reserved 2;
  reserved "branch_types";

  // Required, the name to identify the configuration.
  //
  // The name is arbitrary and is only used for display and human
  // identification.
  string name = 1;

  // The platforms to set for the configuration.
  //
  // The platforms must be strings that can be present in the platforms dict of
  // the project's settings.json.
  //
  // DEPRECATED instead, set one of the fields of the config_type oneof
  repeated string platforms = 3;

  // A sheriff_rotation to apply to the platforms being enabled.
  //
  // DEPRECATED instead, set one of the fields of the config_type oneof
  string sheriff_rotation = 4;

  // A message indicating to run the initialize command of the branch script to
  // set up the branch config
  message InitializeConfig {}

  message PlatformSetConfig {
    // Next ID: 3

    // Required, the platforms to set for the configuration.
    //
    // The platforms must be strings that can be present in the platforms dict
    // of the project's settings.json.
    repeated string platforms = 1;

    // A gardener rotation to apply to the platforms being enabled.
    string gardener_rotation = 2;
  }

  oneof config_type {
    InitializeConfig initialize = 5;
    PlatformSetConfig platform_set = 6;
  }
}

message InputProperties {
  // Next ID: 6

  reserved 2, 3;
  reserved "branch_types", "verification_scripts";

  // Required, the path within the repo to the branch script that can be used to
  // initialize the branch or enable a platform
  //
  // If the initialize_config field is set in the branch config, the script will
  // be called with a command of the form:
  // <branch_script> initialize --milestone <milestone> --branch <branch> --test-config
  // NOTE: The --test-config flag is a test-only flag that ensures the project
  // name isn't changed so that "lucicfg validate" can be executed on the
  // resulting config.
  //
  // If the platform_set or platforms field is set in the branch config, the
  // script will be called with a command of the form:
  // <branch_script> enable-platform <platform> --description <description>
  // It will be executed once for each element in
  // branch_configs[i].platform_set.platforms or branch_configs[i].platforms.
  string branch_script = 1;

  // Required, the branch configs to verify
  repeated BranchConfig branch_configs = 4;

  // Required, the path within the repo to the starlark entry point scripts
  //
  // For each branch config, after the project is reconfigured, each of the
  // entry point scripts will have their config regenerated and validated with
  // the luci-config service. If regenerating or validating fails, then the
  // branch config will be considered a failure and the build's status will be
  // failure.
  repeated string starlark_entry_points = 5;
}
