// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipe_modules.build.chromium_utr;

// Next ID: 16
message Request {
  // Required, the directory where chromium is checked out not including the src
  // dir
  string checkout_path = 1;

  // Test names to run
  //
  // This must match the test names, not their target names to uniquely identify
  // the tests to be run on the builder
  repeated string test_names = 2;

  // The build_dir to use either containing the binary to run or where it is to
  // be compiled
  string build_dir = 3;

  enum RunType {
    RUN_TYPE_RUN = 0;
    RUN_TYPE_COMPILE = 1;
    RUN_TYPE_COMPILE_AND_RUN = 2;
  }

  // Whether or not the recipe should attempt to build and/or build the tests
  RunType run_type = 4;

  // Where to write properties for the next potential runs. Each options will
  // be a string representing what the user should see mapped to alterations
  // to this input proto that should be used for the next run when selected.
  // An empty set of proto implies there is not change and no reason to rerun
  // and should instead abort.
  // The first option should be the default to use as well as the option to use
  // when a --forced run is desired.
  string output_properties_file = 5;

  // Next ID: 7
  message RerunOptions {
    // Skip checking .gclient mismatches
    bool bypass_gclient = 1;

    // Skip checking gn arg mismatches
    bool bypass_gn_args = 2;

    // When true the gn args in the build dir will be preserved. Otherwise
    // the builder gn args will overwrite the file. If code coverage is active
    // and the user chooses to instrument everything, the
    // coverage_instrumentation_input_file arg will still be removed
    bool preserve_gn_args = 3;

    // Skip checking for an upstream branch
    bool bypass_branch_check = 4;

    // How to proceed if the bypass_branch_check is bypassed
    bool skip_instrumentation = 5;

    // Skip verifying the config is compatible with the builder and host
    bool skip_config_validation = 6;
  }

  // The recipe being run by the builder. The 'recipe' input property gets
  // overwritten by the recipe so this property needs to provide this info
  string builder_recipe = 6;

  // Options that are used to re-invoke the recipe
  RerunOptions rerun_options = 7;

  // Any extra cmd-line flags to pass to the tests (eg: "--gtest_filter=...")
  repeated string additional_test_args = 8;

  // If set, will remove all test args normally set for the builder's tests.
  // Likely used in tandem with additional_test_args to override various args.
  bool omit_default_test_args = 15;

  // Custom swarming dimensions to overwrite all tests with in this run
  // These are merged with the tests' existing dimensions. These should
  // be in the form of '{dimension}:{value}'. To remove the value of a
  // dimension, include the dimension with no value.
  repeated string swarming_dimensions = 12;

  // Shard count override for any swarming tests.
  int32 swarming_shards = 13;

  // An optional swarming task id to attempt to reuse the cas digest of
  string reuse_swarming_task = 9;

  // When true, forces rbe to not be used
  bool no_rbe = 10;

  // When true, forces siso to not be used
  bool no_siso = 11;

  // If set, will compile using this path rather than the builder's normal
  // behavior.
  string autoninja_path = 14;
}

message EnvProperties {
  // Used so that the UTR can detect when we're running inside Gemini CLI and
  // change its behavior (eg: limiting output lines).
  string GEMINI_CLI = 1;
}
