// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
syntax = "proto3";

package recipe_modules.build.siso;

// NEXT ID TO USE: 10
message InputProperties {
  // cipd tag for infra_internal/experimental/siso/${platform}
  // TODO(ukai): If empty, it will use siso binary installed in production
  // tree by DEPS.
  string siso_version = 1;

  // Backend config

  // Cloud project ID to use (for RBE, cloud logging, etc).
  string project = 2;

  // The remote execution service to dial gRPC.
  // Default is "remotebuildexecution.googleapis.com:443" in siso binary.
  string reapi_address = 3;

  // RBE instance name (example: "default_instance").
  string reapi_instance = 4;

  // Features

  // Specify a cache silo key.
  // This allows remote build caches to be segregated.
  // It is useful in cases such as performance testing.
  string action_salt = 8;

  // Siso experiments ids.
  // https://chromium.googlesource.com/infra/infra/+/bdc94f6a432b49b0c8412994c095901f816532b8/go/src/infra/build/siso/build/experiments.go#17
  repeated string experiments = 9;
}
