// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
syntax = "proto3";

package recipe_modules.build.siso;

// NEXT ID TO USE: 18
message InputProperties {
  // Backend config

  // Cloud project ID to use (for RBE, cloud logging, etc).
  string project = 1;

  // The remote execution service to dial gRPC.
  // Default is "remotebuildexecution.googleapis.com:443" in siso binary.
  string reapi_address = 2;

  // RBE instance name (example: "default_instance").
  string reapi_instance = 3;

  // Features

  // Specify a cache silo key.
  // This allows remote build caches to be segregated.
  // It is useful in cases such as performance testing.
  string action_salt = 4;

  // Siso experiments ids.
  // https://chromium.googlesource.com/build/+/refs/heads/main/siso/build/experiments.go#:~:text=var%20knownExperiments
  repeated string experiments = 5;

  // monitoring/observability
  bool enable_cloud_profiler = 6;
  bool enable_cloud_trace = 7;
  // Cloud monitoring feature is available only when using the builtin RBE
  // client. When Siso uses Reclient, Reclient sends metrics to Cloud monitoring
  // instead.
  bool enable_cloud_monitoring = 13;
  // GCP project for Cloud Monitoring.
  string metrics_project = 14;

  // Siso configs passed to Starlark config via `--config`.
  // In chromium, available config can be found at
  // https://chromium.googlesource.com/chromium/src/+/refs/heads/main/build/config/siso/config.star
  reserved 8;
  repeated string configs = 9;

  // The number of remote jobs to run in parallel.
  // The default is calculated by Siso internally.
  int32 remote_jobs = 10;

  // Siso limits overrides.
  // https://chromium.googlesource.com/build/+/fac028f33f398558bd6e73380eb3327545751171/siso/build/limits.go#60
  // e.g. limits: "fastlocal=0"
  string limits = 15;

  // Boolean flag to enable REAPI usage check after build step.
  // This is useful to make sure REAPI is not used in the build.
  bool fail_if_reapi_used = 11;

  // Siso flag for `--output_local_strategy`.
  string output_local_strategy = 12;

  // Siso flag for setting `-k`.
  optional int32 keep_going = 16;

  // Disable batch mode for `siso ninja` by setting `-batch=false`.
  bool disable_batch_mode = 17;
}
