#!/usr/bin/env python3
# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import annotations

import argparse
import datetime
import re
import subprocess


def git_log_lines(git_dir, after_date, max_commits):
  cmd = [
    'git',
    '-C',
    git_dir,
    'log',
    '--after',
    str(after_date),
    '-n',
    str(max_commits),
  ]
  stdout = subprocess.check_output(cmd).decode('utf-8')
  return stdout.split('\n')


def extract_change_id(line):
  match = re.search('^\s*Change-Id:\s*(\w*)$', line)
  if not match:
    return None
  return match.group(1)


def parse_args():
  parser = argparse.ArgumentParser(
    prog='Generate Change-IDs file',
    description='Generates a truncated list of Gerrit Change-IDs contained in this build.',
  )
  parser.add_argument(
    '--git_dir',
    type=str,
    help='Path to the git dir the Change-IDs file will be generated for.',
    required=True,
  )
  parser.add_argument(
    '--output_file',
    type=str,
    help='Path to the file where the Change-IDs will be saved.',
    required=True,
  )
  parser.add_argument(
    '--max_commits',
    type=int,
    help='Max number of commits that this script will look into to generate the Change-IDs file.',
    default=100000,
  )
  parser.add_argument(
    '--after_date',
    type=str,
    help='Commits more recent than this date will be used to generate the Change-ID file. See documentation of date formats: https://git-scm.com/docs/git-log#Documentation/git-log.txt---dateltformatgt.',
    default="6 months",
  )
  return parser.parse_args()


def compute_change_ids(git_dir, after_date, max_commits):
  lines = map(
    extract_change_id, git_log_lines(git_dir, after_date, max_commits)
  )
  return filter(lambda x: x is not None, lines)


def main():
  args = parse_args()
  change_ids = compute_change_ids(
    args.git_dir, args.after_date, args.max_commits
  )
  with open(args.output_file, 'w') as f:
    f.write('''# Generated by chromium/tools/build:
# //recipes/recipe_modules/cronet/resources/generate_changelist.py
# Each line is a Gerrit Change ID that is included in this build.
# Note: this is a truncated list.
''')
    for change_id in change_ids:
      f.write(change_id)
      f.write('\n')


if __name__ == '__main__':
  main()
