# Verified and ignored mismatches for reclient compare builders
# Each rule should have a comment with a bug for that mismatch
# The format of this file is a MismatchIgnoreConfig textproto message
# from http://cs/foundry-x-re-client/api/proxy/mismatch_ignore_rule.proto

# crbug/1373836
rules {
    output_file_path_rule_spec {
        path_pattern {
            expression: "obj/third_party/swiftshader/third_party/llvm-10\\.0/swiftshader_llvm_most/Attributes\\.o"
        }
    }
}

# b/281663988
rules {
    output_file_path_rule_spec {
        path_pattern {
            expression: "obj/ui/qt/qt[5,6]?_shim/qt[5,6]?_shim(?:_moc)?\\.o(?:\\.d)?"
        }
    }
}
rules {
    output_file_path_rule_spec {
        path_pattern {
            expression: "obj/ui/qt/qt_interface/qt_interface\\.o(?:\\.d)?"
        }
    }
}

# crbug/1497905, b/298688400
rules {
    output_file_path_rule_spec {
        path_pattern {
            expression: "^\.\.\/\.\.\/tools\/clang\/crashreports$"
        }
    }
}
