// Copyright 2023 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package recipes.build.art;

message InputProperties {
  // use_props is a temporary property to allow for a soft transition over to
  // properties. When set to true, the recipe will use properties, otherwise
  // properties will be determined by the builder name.
  bool use_props = 1;

  // Whether to build with debug symbols.
  bool debug = 2;

  // What target device to build for. If unset, the recipe will run in host mode.
  string device = 3;

  // The bitness of the target architecture to build for.
  int64 bitness = 4;

  // Which repo manifest branch to use. If unset, default is 'master-art'.
  string manifest_branch = 5;

  // Whether to enable the heap_poisoning build variant.
  bool heap_poisoning = 6;

  // Whether to enable the concurrent_collector build variant.
  bool concurrent_collector = 7;

  // Whether to enable the gcstress build variant.
  bool gcstress = 8;

  // Whether to enable the generational_cc build variant.
  bool generational_cc = 9;

  // What level of cdex to use, default is 'none'.
  string cdex_level = 10;

  // Whether to boot up a virtual machine before running tests.
  bool on_virtual_machine = 11;

  // Whether to exit early after building or run the full test suite.
  // Used as an intermediary while builds are functional but tests are not.
  bool build_only = 12;
}
