# Copyright 2022 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import base64
import collections
import zlib

from PB.go.chromium.org.luci.buildbucket.proto import common as common_pb2
from PB.go.chromium.org.luci.common.proto.findings import findings as findings_pb
from recipe_engine import post_process

from dataclasses import dataclass

from recipe_engine.recipe_api import RecipeScriptApi
from recipe_engine.recipe_test_api import RecipeTestApi

from RECIPE_MODULES.build import chromium
from RECIPE_MODULES.depot_tools import gerrit, tryserver
from RECIPE_MODULES.recipe_engine import (
    buildbucket,
    findings,
    json,
    platform,
    proto,
    random,
    step,
    swarming,
)


@dataclass
class DEPS(RecipeScriptApi):
  buildbucket: buildbucket.API
  chromium: chromium.API
  findings: findings.API
  gerrit: gerrit.API
  json: json.API
  platform: platform.API
  proto: proto.API
  random: random.API
  step: step.API
  swarming: swarming.API
  tryserver: tryserver.API


@dataclass
class TEST_DEPS(RecipeTestApi):
  buildbucket: buildbucket.TEST_API
  chromium: chromium.TEST_API
  gerrit: gerrit.TEST_API
  json: json.TEST_API
  platform: platform.TEST_API
  proto: proto.TEST_API
  random: random.TEST_API
  tryserver: tryserver.TEST_API

# TODO(crbug.com/1153919): Figure out which subset of these are the best
# trade-off between coverage/cost and enable them.
_CHILD_BUILDERS = (
    'android-clang-tidy-rel',
    # TODO(1444563): Add back once error count is brought back down.
    #'linux-chromeos-clang-tidy-rel',
    'linux-clang-tidy-rel',
    #'linux-lacros-clang-tidy-rel',
    #'fuchsia-clang-tidy-rel',
    #'ios-clang-tidy-rel',
    #'mac-clang-tidy-rel',
    #'win10-clang-tidy-rel',
)
_CONDITIONAL_CHILD_BUILDERS = (
    'mac-clang-tidy-rel',
)
# Probability for including the conditional builder
_CONDITIONAL_PROBABILITY = 0.20


def _should_skip_linting(api):
  revision_info = api.gerrit.get_revision_info(
      'https://%s' % api.tryserver.gerrit_change.host,
      api.tryserver.gerrit_change.change, api.tryserver.gerrit_change.patchset)

  # TODO(gbiv): It may be nice to be more consistent in how we check for
  # whether something's lintable. At the time of writing, this heuristic is
  # what's being used for linux-clang-tidy-rel's recipe, but:
  # - tricium_simple does something different entirely
  # - this heuristic doesn't perfectly cover all reverts
  # - it'd be nice to skip autogenerated CLs entirely (crbug.com/872381)
  commit_message = revision_info['commit']['message']
  return commit_message.startswith('Revert')


def _build_textual_bot_list(bots, conjunction):
  """Converts a list of bots into a human readable string listing them."""
  bots = ['`%s`' % x for x in bots]
  if not bots:
    return ''

  if len(bots) == 1:
    return bots[0]

  return ' '.join((', '.join(bots[:-1]), conjunction, bots[-1]))


def _note_observed_on(platforms, all_platforms, finding):
  """Append the finding message with observed platforms

  >>> _note_observed_on(['foo'], ['foo', 'bar'], some_finding)
  some_finding.message += '\n\n(Lint observed on foo, but not bar)'
  >>> _note_observed_on(['foo', 'bar'], ['foo', 'bar'], some_lint)
  some_finding.message += '\n\n(Lint observed on foo and bar)'
  >>> _note_observed_on(['foo'], ['foo', 'bar', 'baz'], some_lint)
  some_finding.message += '\n\n(Lint observed on foo, but not bar or baz)'
  """
  msg = 'Lint observed on ' + _build_textual_bot_list(
      platforms,
      conjunction='and',
  )
  platforms_set = set(platforms)
  not_observed_on = _build_textual_bot_list(
      (p for p in all_platforms if p not in platforms_set),
      conjunction='or',
  )
  if not_observed_on:
    msg += ', but not on ' + not_observed_on
  finding.message += f'\n\n({msg})'


def _fixup_path(file_path):
  # Filter out certain third_party paths if present. Chromium will not have
  # these entries in the results because they are pulled in from Deps. These
  # show up when running clang-tidy on changes in their respective gerrit
  # instances where the prefix needs to be stripped.
  third_party_paths_to_strip = [
      'third_party/dawn/', 'third_party/boringssl/src/'
  ]
  for path_to_strip in third_party_paths_to_strip:
    file_path = file_path.removeprefix(path_to_strip)
  return file_path


def _fixup_finding_paths(finding):
  # Fixup all the paths for a particular finding.
  finding.location.file_path = _fixup_path(finding.location.file_path)
  for f in finding.fixes:
    for r in f.replacements:
      r.location.file_path = _fixup_path(r.location.file_path)


def _dedup_findings(api, all_platforms, findings_by_platform):
  platforms_by_encoded_finding = collections.defaultdict(list)
  for platform, findings in findings_by_platform.items():
    for f in findings:
      # sort the replacements and fixes to de-duplicate findings with same
      # fixes and replacements but in different order.
      if f.fixes:
        for fix in f.fixes:
          fix.replacements.sort(key=lambda r: (
              r.location.file_path,
              r.location.range.start_line,
              r.location.range.start_column,
              r.location.range.end_line,
              r.location.range.end_column,
              r.new_content,
          ))
        f.fixes.sort(key=lambda f: (
            f.replacements[0].location.file_path,
            f.replacements[0].location.range.start_line,
            f.replacements[0].location.range.start_column,
            f.replacements[0].location.range.end_line,
            f.replacements[0].location.range.end_column,
            f.replacements[0].new_content,
        ))
      encoded_finding = api.proto.encode(f, 'BINARY')
      platforms_by_encoded_finding[encoded_finding].append(platform)

  results = []
  for encoded_finding, observed_on in platforms_by_encoded_finding.items():
    finding = api.proto.decode(encoded_finding, findings_pb.Finding, 'BINARY')
    _note_observed_on(observed_on, all_platforms, finding)
    results.append(finding)
  return results


def RunSteps(api: DEPS):
  assert api.tryserver.is_tryserver

  api.buildbucket.hide_current_build_in_gerrit()

  if _should_skip_linting(api):
    return

  # Limit children to a fraction of our timeout. If our timeout is very
  # long, 1 hour should be plenty.
  #
  # Child timeouts are most often caused by one of two things:
  #  1. Massive CLs
  #  2. Children trying very hard to find a header file (that other children
  #     were able to promptly find).
  #
  # In the former case, there's not much we can do to speed things up. In the
  # latter, our goal should be to post the lints of the children that finished
  # before the timeout, rather than having the orchestrator itself time out and
  # drop that information on the floor.
  my_execution_timeout = api.buildbucket.build.execution_timeout
  child_execution_timeout_secs = min(my_execution_timeout.ToSeconds() // 2,
                                     3600)

  with api.step.nest('schedule tidy builds'):
    builders_to_schedule = list(_CHILD_BUILDERS)
    # Enables the builders in _CONDITIONAL_CHILD_BUILDERS for ~20% of the time.
    if api.random.random() < _CONDITIONAL_PROBABILITY:
      builders_to_schedule.extend(_CONDITIONAL_CHILD_BUILDERS)
    build_requests = [
        api.buildbucket.schedule_request(
            x,
            swarming_parent_run_id=api.swarming.task_id,
            tags=api.buildbucket.tags(**{'hide-in-gerrit': 'true'}),
            as_shadow_if_parent_is_led=True,
        ) for x in builders_to_schedule
    ]

    for req in build_requests:
      req.execution_timeout.FromSeconds(child_execution_timeout_secs)

    builds = api.buildbucket.schedule(build_requests, step_name='schedule')
    build_ids = [x.id for x in builds]
    build_dict = api.buildbucket.collect_builds(
        build_ids,
        fields=('output', 'status'),
        # Multiply by 1.5 here to account for slack in scheduling/etc.
        timeout=int(child_execution_timeout_secs * 1.5),
    )

    num_failures = sum(
        1 for x in build_dict.values() if x.status != common_pb2.SUCCESS)
    had_failures = num_failures != 0
    all_failures = num_failures == len(builds)

    if had_failures:
      presentation = api.step.active_result.presentation
      presentation.status = api.step.WARNING
      presentation.step_text = "%d/%d builds failed" % (num_failures,
                                                        len(builds))

    builds = [
        (x, build_dict[i]) for x, i in zip(builders_to_schedule, build_ids)
    ]

  with api.step.nest('analyze lints'):
    findings_by_builder = {}
    for builder_name, build_result in builds:
      properties = build_result.output.properties
      if 'findings' not in properties:
        continue
      binary_encoded_findings = zlib.decompress(
          base64.b64decode(properties['findings'].encode()))
      findings_by_builder[builder_name] = api.proto.decode(
          binary_encoded_findings, findings_pb.Findings, 'BINARY').findings

    findings = _dedup_findings(api, builders_to_schedule, findings_by_builder)
    if findings:
      for f in findings:
        _fixup_finding_paths(f)
      api.findings.upload_findings(findings, step_name='upload findings')

  if all_failures:
    # crbug.com/1343619: There are many reasons that a bot may fail (a broken
    # patch being one of the key ones). That said, if one's patches aren't
    # recent enough (mid-Jun 2022), they may see constant clang-tidy redness.
    # Make the fix obvious for those cases.
    raise api.step.StepFailure('All sub-linting tasks failed. This may be '
                               'because your change needs to be rebased past '
                               'src@522320443539084c901edd659dd29079c8aaadc0. '
                               'Please note that clang-tidy failures do not '
                               'block the CQ.')


def GenTests(api: TEST_DEPS):
  gerrit_change_ref = findings_pb.Location.GerritChangeReference(
      host='chromium-review.googlesource.com',
      project='chromium/src',
      change=12345,
      patchset=1)

  def test_data(include_conditional=False,
                findings_by_builder=None,
                bot_status_overrides=None,
                commit_message='foo'):
    # Determine the full list of builders this test simulation should cover
    simulated_builders = list(_CHILD_BUILDERS)
    if include_conditional:
      simulated_builders.extend(_CONDITIONAL_CHILD_BUILDERS)
    test_data = sum([
        api.chromium.try_build(
            builder_group='tryserver.chromium.linux',
            builder='linux_chromium_compile_rel_ng',
            build_number=1234,
            change_number=gerrit_change_ref.change,
            patch_set=gerrit_change_ref.patchset),
        api.platform('linux', 64),
        api.override_step_data(
            'gerrit changes',
            api.json.output([{
                'revisions': {
                    'a' * 40: {
                        '_number': 1,
                        'commit': {
                            'author': {
                                'email': 'gbiv@google.com',
                            },
                            'message': commit_message,
                        }
                    }
                }
            }]))
    ], api.empty_test_data())

    if commit_message.startswith('Revert'):
      return test_data

    if bot_status_overrides is None:
      bot_status_overrides = {}

    # Magic unexported number from buildbucket/api.py; test build IDs are
    # generated sequentially from this, and there're a few other recipes that
    # depend on this number directly.
    base_id = 8922054662172514000
    build_ids = list(range(base_id, base_id + len(simulated_builders)))
    build_output = [
        api.buildbucket.try_build_message(
            build_id=i,
            status=bot_status_overrides.get(builder_name, 'SUCCESS'),
        ) for i, builder_name in zip(build_ids, simulated_builders)
    ]

    if findings_by_builder:
      builder_indices = {n: i for i, n in enumerate(simulated_builders)}
      for builder_name, findings in findings_by_builder.items():
        if findings is not None:
          n = builder_indices[builder_name]
          build_output[n].output.properties['findings'] = base64.b64encode(
              zlib.compress(
                  api.proto.encode(
                      findings_pb.Findings(findings=findings),
                      'BINARY'))).decode()

    test_data += api.buildbucket.simulated_collect_output(
        build_output,
        step_name='schedule tidy builds.buildbucket.collect',
    )
    return test_data

  def _get_uploaded_findings(steps):
    if 'analyze lints.upload findings' not in steps or (
        'findings.json' not in steps['analyze lints.upload findings'].logs):
      return []
    findings_json = steps['analyze lints.upload findings'].logs['findings.json']
    return api.proto.decode(findings_json, findings_pb.Findings,
                            'JSONPB').findings

  def _has_no_finding(check, steps):
    check(not _get_uploaded_findings(steps))

  def _has_finding(check, steps, finding):
    findings = _get_uploaded_findings(steps)
    check(findings)
    if findings:
      check(finding in findings)

  yield api.test(
      'skip_reverted_cl',
      test_data(findings_by_builder=None, commit_message='Revert foo'),
      api.post_process(post_process.DoesNotRun, 'schedule tidy builds'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'success_on_no_findings',
      test_data(findings_by_builder=None),
      api.post_process(_has_no_finding),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'success_on_empty_findings_output',
      test_data(findings_by_builder={name: [] for name in _CHILD_BUILDERS}),
      api.post_process(_has_no_finding),
      api.post_process(post_process.DropExpectation),
  )

  finding = findings_pb.Finding(
      category='some_category',
      location=findings_pb.Location(
          gerrit_change_ref=gerrit_change_ref,
          file_path='foo.cpp',
      ),
      message='some message',
      severity_level=findings_pb.Finding.SEVERITY_LEVEL_WARNING,
  )
  expected_finding = findings_pb.Finding()
  expected_finding.CopyFrom(finding)
  _note_observed_on([_CHILD_BUILDERS[0]], _CHILD_BUILDERS, expected_finding)
  yield api.test(
      'basic_tidy_output_works',
      test_data(findings_by_builder={_CHILD_BUILDERS[0]: [finding]}),
      api.post_process(_has_finding, expected_finding),
      api.post_process(post_process.DropExpectation),
  )

  expected_finding = findings_pb.Finding()
  expected_finding.CopyFrom(finding)
  _note_observed_on([_CHILD_BUILDERS[0], _CHILD_BUILDERS[1]], _CHILD_BUILDERS,
                    expected_finding)
  yield api.test(
      'multibot_tidy_output_works',
      test_data(findings_by_builder={
          _CHILD_BUILDERS[0]: [finding],
          _CHILD_BUILDERS[1]: [finding],
      }),
      api.post_process(_has_finding, expected_finding),
      api.post_process(post_process.DropExpectation),
  )

  another_finding = findings_pb.Finding(
      category='another_category',
      location=findings_pb.Location(
          gerrit_change_ref=gerrit_change_ref,
          file_path='foo2.cpp',
      ),
      message='some other message',
      severity_level=findings_pb.Finding.SEVERITY_LEVEL_WARNING)
  expected_finding = findings_pb.Finding()
  expected_finding.CopyFrom(finding)
  _note_observed_on([_CHILD_BUILDERS[0], _CHILD_BUILDERS[1]], _CHILD_BUILDERS,
                    expected_finding)
  expected_another_finding = findings_pb.Finding()
  expected_another_finding.CopyFrom(another_finding)
  _note_observed_on([_CHILD_BUILDERS[1]], _CHILD_BUILDERS,
                    expected_another_finding)
  yield api.test(
      'multibot_multicomment_tidy_output_works',
      test_data(
          findings_by_builder={
              _CHILD_BUILDERS[0]: [finding],
              _CHILD_BUILDERS[1]: [finding, another_finding],
          }),
      api.post_process(_has_finding, expected_finding),
      api.post_process(_has_finding, expected_another_finding),
      api.post_process(post_process.DropExpectation),
  )

  finding_with_fixes = findings_pb.Finding(
      category='some_category',
      location=findings_pb.Location(
          gerrit_change_ref=gerrit_change_ref,
          file_path='foo.cpp',
      ),
      message='some message',
      severity_level=findings_pb.Finding.SEVERITY_LEVEL_WARNING,
      fixes=[
          findings_pb.Fix(replacements=[
              findings_pb.Fix.Replacement(
                  new_content='replaced',
                  location=findings_pb.Location(
                      gerrit_change_ref=gerrit_change_ref,
                      file_path='path/to/bar.cc',
                      range=findings_pb.Location.Range(
                          start_line=1,
                          start_column=1,
                          end_line=1,
                          end_column=2,
                      ),
                  ),
              ),
              findings_pb.Fix.Replacement(
                  new_content='replaced',
                  location=findings_pb.Location(
                      gerrit_change_ref=gerrit_change_ref,
                      file_path='path/to/bar.cc',
                      range=findings_pb.Location.Range(
                          start_line=3,
                          start_column=0,
                          end_line=4,
                          end_column=5,
                      ),
                  ),
              ),
          ]),
          findings_pb.Fix(replacements=[
              findings_pb.Fix.Replacement(
                  new_content='replaced',
                  location=findings_pb.Location(
                      gerrit_change_ref=gerrit_change_ref,
                      file_path='path/to/foo.cc',
                  ),
              ),
          ]),
      ])
  finding_with_same_fixes = findings_pb.Finding(
      category='some_category',
      location=findings_pb.Location(
          gerrit_change_ref=gerrit_change_ref,
          file_path='foo.cpp',
      ),
      message='some message',
      severity_level=findings_pb.Finding.SEVERITY_LEVEL_WARNING,
      fixes=[
          findings_pb.Fix(replacements=[
              findings_pb.Fix.Replacement(
                  new_content='replaced',
                  location=findings_pb.Location(
                      gerrit_change_ref=gerrit_change_ref,
                      file_path='path/to/foo.cc',
                  ),
              ),
          ]),
          findings_pb.Fix(replacements=[
              findings_pb.Fix.Replacement(
                  new_content='replaced',
                  location=findings_pb.Location(
                      gerrit_change_ref=gerrit_change_ref,
                      file_path='path/to/bar.cc',
                      range=findings_pb.Location.Range(
                          start_line=3,
                          start_column=0,
                          end_line=4,
                          end_column=5,
                      ),
                  ),
              ),
              findings_pb.Fix.Replacement(
                  new_content='replaced',
                  location=findings_pb.Location(
                      gerrit_change_ref=gerrit_change_ref,
                      file_path='path/to/bar.cc',
                      range=findings_pb.Location.Range(
                          start_line=1,
                          start_column=1,
                          end_line=1,
                          end_column=2,
                      ),
                  ),
              ),
          ]),
      ])
  expected_finding = findings_pb.Finding()
  expected_finding.CopyFrom(finding_with_fixes)
  _note_observed_on([_CHILD_BUILDERS[0], _CHILD_BUILDERS[1]], _CHILD_BUILDERS,
                    expected_finding)
  yield api.test(
      'deduplicate_semantically_same_findings',
      test_data(
          findings_by_builder={
              _CHILD_BUILDERS[0]: [finding_with_fixes],
              _CHILD_BUILDERS[1]: [finding_with_same_fixes],
          }),
      api.post_process(_has_finding, expected_finding),
      api.post_process(post_process.DropExpectation),
  )

  all_builders_with_cond = list(_CHILD_BUILDERS) + list(
      _CONDITIONAL_CHILD_BUILDERS)
  expected_finding_with_cond = findings_pb.Finding()
  expected_finding_with_cond.CopyFrom(finding)
  _note_observed_on([_CHILD_BUILDERS[1]] + list(_CONDITIONAL_CHILD_BUILDERS),
                    all_builders_with_cond, expected_finding_with_cond)
  yield api.test(
      'single_bot_failure_with_conditional',
      api.random.seed(1),
      test_data(
          include_conditional=True,
          bot_status_overrides={_CHILD_BUILDERS[0]: 'FAILURE'},
          findings_by_builder={
              _CHILD_BUILDERS[1]: [finding
                                  ],  # Findings for successful base builder
              # Assume conditional builders succeed and also find 'finding'
              _CONDITIONAL_CHILD_BUILDERS[0]: [finding],
          }),
      api.post_process(post_process.StepWarning, 'schedule tidy builds'),
      api.post_process(_has_finding, expected_finding_with_cond),
      api.post_process(post_process.DropExpectation),
  )

  step_failure = 'FAILURE'
  expected_finding = findings_pb.Finding()
  expected_finding.CopyFrom(finding)
  _note_observed_on([_CHILD_BUILDERS[0], _CHILD_BUILDERS[1]], _CHILD_BUILDERS,
                    expected_finding)
  yield api.test(
      'single_bot_failure',
      api.random.seed(1234),
      test_data(
          include_conditional=False,
          bot_status_overrides={
              _CHILD_BUILDERS[0]: step_failure,
          },
          findings_by_builder={
              _CHILD_BUILDERS[0]: [finding],
              _CHILD_BUILDERS[1]: [finding],
          }),
      api.post_process(post_process.StepWarning, 'schedule tidy builds'),
      api.post_process(_has_finding, expected_finding),
      api.post_process(post_process.DropExpectation),
  )

  all_builders_with_cond_list = list(_CHILD_BUILDERS) + list(
      _CONDITIONAL_CHILD_BUILDERS)
  expected_finding = findings_pb.Finding()
  expected_finding.CopyFrom(finding)
  _note_observed_on([_CHILD_BUILDERS[0], _CONDITIONAL_CHILD_BUILDERS[0]],
                    all_builders_with_cond_list, expected_finding)
  yield api.test(
      'success_with_conditional',
      api.random.seed(1),
      test_data(
          include_conditional=True,
          findings_by_builder={
              _CHILD_BUILDERS[0]: [finding],
              _CONDITIONAL_CHILD_BUILDERS[0]: [finding],
          }),
      api.post_process(_has_finding, expected_finding),
      api.post_process(post_process.StatusSuccess),
      api.post_process(post_process.StepSuccess, 'schedule tidy builds'),
      api.post_process(post_process.DropExpectation),
  )

  expected_finding = findings_pb.Finding()
  expected_finding.CopyFrom(finding)
  _note_observed_on(_CHILD_BUILDERS, _CHILD_BUILDERS, expected_finding)
  yield api.test(
      'all_bot_failure',
      test_data(
          bot_status_overrides={
              builder: step_failure for builder in _CHILD_BUILDERS
          },
          findings_by_builder={
              builder: [finding] for builder in _CHILD_BUILDERS
          }),
      api.expect_status('FAILURE'),
      api.post_process(post_process.StepWarning, 'schedule tidy builds'),
      api.post_process(_has_finding, expected_finding),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'all_bot_failure_with_conditional',
      api.random.seed(1),
      test_data(
          include_conditional=True,
          bot_status_overrides={
              builder: 'FAILURE'
              for builder in (list(_CHILD_BUILDERS) +
                              list(_CONDITIONAL_CHILD_BUILDERS))
          },
          findings_by_builder=None),
      api.expect_status('FAILURE'),
      api.post_process(post_process.StepWarning, 'schedule tidy builds'),
      api.post_process(post_process.SummaryMarkdownRE,
                       'All sub-linting tasks failed'),
      api.post_process(_has_no_finding),
      api.post_process(post_process.DropExpectation),
  )

  finding_dawn = findings_pb.Finding(
      category='dawn_category',
      location=findings_pb.Location(
          gerrit_change_ref=gerrit_change_ref,
          file_path='third_party/dawn/src/tint/foo2.cpp',
      ),
      message='some message',
      severity_level=findings_pb.Finding.SEVERITY_LEVEL_WARNING,
      fixes=[
          findings_pb.Fix(replacements=[
              findings_pb.Fix.Replacement(
                  new_content='replaced',
                  location=findings_pb.Location(
                      gerrit_change_ref=gerrit_change_ref,
                      file_path='third_party/dawn/src/tint/foo.cc',
                  ),
              ),
          ])
      ])
  expected_finding_dawn = findings_pb.Finding()
  expected_finding_dawn.CopyFrom(finding_dawn)
  _note_observed_on([_CHILD_BUILDERS[0]], _CHILD_BUILDERS,
                    expected_finding_dawn)
  expected_finding_dawn.location.file_path = 'src/tint/foo2.cpp'
  expected_finding_dawn.fixes[0].replacements[
      0].location.file_path = 'src/tint/foo.cc'
  yield api.test(
      'filter_dawn_paths',
      test_data(findings_by_builder={_CHILD_BUILDERS[0]: [finding_dawn]}),
      api.post_process(_has_finding, expected_finding_dawn),
      api.post_process(post_process.DropExpectation),
  )
